// ============================================================
// ワインエキスパート2次試験 テイスティングコメント練習 データ
// ------------------------------------------------------------
// ※ 用語・選択数は J.S.A. の解答用紙を参考にした近似です。
//    お手元の最新の本番シートに合わせて自由に編集してください。
//    terms / pick / 模範解答(answers) を書き換えるだけで反映されます。
// ============================================================

const VOCAB = {
  white: [
    { id: "clarity",    group: "外観", title: "清澄度", pick: 1,
      terms: ["澄んだ", "やや濁った", "濁った"] },
    { id: "brightness", group: "外観", title: "輝き", pick: 1,
      terms: ["輝きのある", "モヤがかった"] },
    { id: "color",      group: "外観", title: "色調", pick: 2,
      terms: ["グリーンがかった", "レモンイエロー", "イエロー", "黄金色がかった", "トパーズ", "アンバー"] },
    { id: "intensity",  group: "外観", title: "濃淡", pick: 1,
      terms: ["無色に近い", "淡い", "やや淡い", "やや濃い", "濃い"] },
    { id: "viscosity",  group: "外観", title: "粘性", pick: 1,
      terms: ["さらっとした", "やや軽い", "やや強い", "強い"] },
    { id: "appearanceImpression", group: "外観", title: "外観の印象", pick: 2,
      terms: ["若々しい", "軽快な", "よく熟した", "濃縮感がある", "成熟度が高い", "酸化熟成のニュアンス", "酸化が進んだ"] },
    { id: "aromaFirst", group: "香り", title: "第一印象", pick: 2,
      terms: ["閉じている", "控えめ", "開いている", "しっかりと感じられる", "強い", "華やかな"] },
    { id: "aromaFruit", group: "香り", title: "特徴（果実・花・植物）", pick: 4,
      terms: ["柑橘類", "青リンゴ", "リンゴ", "洋梨", "カリン", "白桃", "アプリコット", "パイナップル",
              "マンゴー", "パッションフルーツ", "ライチ", "マスカット", "アカシア", "白バラ", "キンモクセイ",
              "スイカズラ", "菩提樹", "カモミール", "ハーブ", "ミント", "アニス", "火打石", "貝殻", "石灰"] },
    { id: "aromaSpice", group: "香り", title: "特徴（香辛料・芳香・化学物質）", pick: 2,
      terms: ["白コショウ", "コリアンダー", "ナツメグ", "丁子", "バニラ", "トースト", "ナッツ", "バター",
              "蜂蜜", "ヨード香", "硫黄", "ペトロール", "杏仁豆腐", "樹脂"] },
    { id: "aromaImpression", group: "香り", title: "香りの印象", pick: 2,
      terms: ["若々しい", "華やかな", "芳醇な", "熟成感が現れている", "酸化熟成の段階にある", "ニュートラルな",
              "第1アロマが強い", "第2アロマが強い", "樽からのニュアンス"] },
    { id: "attack",   group: "味わい", title: "アタック", pick: 1,
      terms: ["軽い", "やや軽い", "やや強い", "強い"] },
    { id: "sweetness", group: "味わい", title: "甘み（アルコールのボリューム感を含む）", pick: 1,
      terms: ["弱い", "まろやかな", "豊かな", "残糖がある"] },
    { id: "acidity",  group: "味わい", title: "酸味", pick: 1,
      terms: ["シャープな", "爽やかな", "なめらかな", "まろやかな", "おだやかな"] },
    { id: "bitterness", group: "味わい", title: "苦味", pick: 1,
      terms: ["控えめ", "穏やかな", "コク（深み）を与える", "強い"] },
    { id: "balance",  group: "味わい", title: "バランス", pick: 2,
      terms: ["スリムな", "溌剌とした", "ドライな", "コンパクトな", "まろやかな", "ジューシーな",
              "豊満な", "力強い", "厚みのある", "骨格のしっかりした"] },
    { id: "alcohol",  group: "味わい", title: "アルコール", pick: 1,
      terms: ["弱い", "やや軽め", "中程度", "やや強め", "熱さを感じる"] },
    { id: "finish",   group: "味わい", title: "余韻", pick: 1,
      terms: ["短い", "やや短い", "やや長い", "長い"] },
    { id: "evaluation", group: "総合評価", title: "評価", pick: 1,
      terms: ["シンプル、フレッシュ感を楽しむ", "成熟度が高く豊かな", "濃縮し力強い",
              "エレガントで余韻の長い", "ポテンシャルのある"] },
    { id: "temperature", group: "総合評価", title: "適正温度", pick: 1,
      terms: ["8度未満", "8～10度", "11～14度", "15～18度"] },
    { id: "glass",    group: "総合評価", title: "供出グラス", pick: 1,
      terms: ["小ぶり", "中庸", "大ぶり"] },
    { id: "vintage",  group: "結論", title: "収穫年", pick: 1,
      terms: ["2019年", "2020年", "2021年", "2022年", "2023年", "2024年"] },
    { id: "country",  group: "結論", title: "生産国", pick: 1,
      terms: ["フランス", "イタリア", "スペイン", "ドイツ", "オーストリア", "アメリカ",
              "オーストラリア", "ニュージーランド", "チリ", "アルゼンチン", "南アフリカ", "日本"] },
    { id: "grape",    group: "結論", title: "ぶどう品種", pick: 1,
      terms: ["シャルドネ", "ソーヴィニヨン・ブラン", "リースリング", "甲州", "ゲヴュルツトラミネール",
              "ミュスカデ", "シュナン・ブラン", "ヴィオニエ", "アルバリーニョ", "トロンテス"] },
  ],

  red: [
    { id: "clarity",    group: "外観", title: "清澄度", pick: 1,
      terms: ["澄んだ", "やや濁った", "濁った"] },
    { id: "brightness", group: "外観", title: "輝き", pick: 1,
      terms: ["輝きのある", "モヤがかった"] },
    { id: "color",      group: "外観", title: "色調", pick: 2,
      terms: ["紫がかった", "ルビー", "ガーネット", "ダークチェリーレッド", "レンガ色がかった",
              "オレンジがかった", "黒みを帯びた"] },
    { id: "intensity",  group: "外観", title: "濃淡", pick: 1,
      terms: ["明るい", "やや明るい", "やや濃い", "濃い", "非常に濃い"] },
    { id: "viscosity",  group: "外観", title: "粘性", pick: 1,
      terms: ["さらっとした", "やや軽い", "やや強い", "強い"] },
    { id: "appearanceImpression", group: "外観", title: "外観の印象", pick: 2,
      terms: ["若々しい", "軽快な", "よく熟した", "濃縮感がある", "熟成のニュアンス", "酸化が進んだ"] },
    { id: "aromaFirst", group: "香り", title: "第一印象", pick: 2,
      terms: ["閉じている", "控えめ", "開いている", "しっかりと感じられる", "強い", "華やかな"] },
    { id: "aromaFruit", group: "香り", title: "特徴（果実・花・植物）", pick: 4,
      terms: ["イチゴ", "ラズベリー", "ブルーベリー", "カシス", "ブラックチェリー", "ブラックベリー",
              "干しプラム", "乾燥イチジク", "スミレ", "バラ", "ボタン", "ゼラニウム", "メントール",
              "針葉樹", "ユーカリ", "ピーマン", "紅茶", "腐葉土", "キノコ", "スーボワ", "タバコ"] },
    { id: "aromaSpice", group: "香り", title: "特徴（香辛料・芳香・化学物質）", pick: 2,
      terms: ["甘草", "黒コショウ", "シナモン", "丁子", "ナツメグ", "バニラ", "ロースト", "コーヒー",
              "チョコレート", "土", "なめし革", "肉", "血液", "ヨード", "樹脂"] },
    { id: "aromaImpression", group: "香り", title: "香りの印象", pick: 2,
      terms: ["若々しい", "華やかな", "芳醇な", "熟成感が現れている", "酸化熟成の段階にある", "ニュートラルな",
              "第1アロマが強い", "第2アロマが強い", "樽からのニュアンス"] },
    { id: "attack",   group: "味わい", title: "アタック", pick: 1,
      terms: ["軽い", "やや軽い", "やや強い", "強い"] },
    { id: "sweetness", group: "味わい", title: "甘み（アルコールのボリューム感を含む）", pick: 1,
      terms: ["弱い", "まろやかな", "豊かな"] },
    { id: "acidity",  group: "味わい", title: "酸味", pick: 1,
      terms: ["シャープな", "爽やかな", "なめらかな", "円みのある", "やわらかな"] },
    { id: "tannin",   group: "味わい", title: "タンニン分", pick: 1,
      terms: ["サラサラとした", "緻密", "ビロードのような", "力強い", "収斂性のある"] },
    { id: "balance",  group: "味わい", title: "バランス", pick: 2,
      terms: ["スマートな", "流れるような", "固い", "骨格のしっかりした", "肉厚な", "力強い",
              "豊満な", "バランスのよい"] },
    { id: "alcohol",  group: "味わい", title: "アルコール", pick: 1,
      terms: ["弱い", "やや軽め", "中程度", "やや強め", "熱さを感じる"] },
    { id: "finish",   group: "味わい", title: "余韻", pick: 1,
      terms: ["短い", "やや短い", "やや長い", "長い"] },
    { id: "evaluation", group: "総合評価", title: "評価", pick: 1,
      terms: ["シンプル、フレッシュ感を楽しむ", "成熟度が高く豊かな", "濃縮し力強い",
              "エレガントで余韻の長い", "ポテンシャルのある"] },
    { id: "temperature", group: "総合評価", title: "適正温度", pick: 1,
      terms: ["8～10度", "11～14度", "15～18度", "19度以上"] },
    { id: "glass",    group: "総合評価", title: "供出グラス", pick: 1,
      terms: ["小ぶり", "中庸", "大ぶり"] },
    { id: "decant",   group: "総合評価", title: "デカンタージュ", pick: 1,
      terms: ["必要なし", "事前に（30分以上前）", "直前"] },
    { id: "vintage",  group: "結論", title: "収穫年", pick: 1,
      terms: ["2018年", "2019年", "2020年", "2021年", "2022年", "2023年"] },
    { id: "country",  group: "結論", title: "生産国", pick: 1,
      terms: ["フランス", "イタリア", "スペイン", "ドイツ", "アメリカ", "オーストラリア",
              "ニュージーランド", "チリ", "アルゼンチン", "南アフリカ", "日本"] },
    { id: "grape",    group: "結論", title: "ぶどう品種", pick: 1,
      terms: ["ピノ・ノワール", "カベルネ・ソーヴィニヨン", "メルロ", "シラー（シラーズ）", "サンジョヴェーゼ",
              "テンプラニーリョ", "ガメイ", "グルナッシュ", "ネッビオーロ", "ジンファンデル", "マスカット・ベーリーA"] },
  ],
};

// ------------------------------------------------------------
// 模範解答つきワインリスト
// answers のキーは上の VOCAB の id に対応。値は「選ぶべき用語」の配列。
// ------------------------------------------------------------
const WINES = [
  {
    id: "sb-nz",
    color: "white",
    label: "白ワイン A",
    name: "ソーヴィニヨン・ブラン（ニュージーランド 2023）",
    note: "ハーブと柑橘、パッションフルーツの香りが特徴。シャープな酸とフレッシュ感が決め手。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "レモンイエロー"], intensity: ["淡い"], viscosity: ["やや軽い"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["しっかりと感じられる", "華やかな"],
      aromaFruit: ["柑橘類", "パッションフルーツ", "ハーブ", "ミント"],
      aromaSpice: ["白コショウ", "硫黄"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["やや軽い"], sweetness: ["弱い"], acidity: ["シャープな"], bitterness: ["控えめ"],
      balance: ["スリムな", "溌剌とした"], alcohol: ["中程度"], finish: ["やや長い"],
      evaluation: ["シンプル、フレッシュ感を楽しむ"], temperature: ["8～10度"], glass: ["小ぶり"],
      vintage: ["2023年"], country: ["ニュージーランド"], grape: ["ソーヴィニヨン・ブラン"],
    },
  },
  {
    id: "ch-fr",
    color: "white",
    label: "白ワイン B",
    name: "シャルドネ（フランス 2022・樽熟成）",
    note: "熟したリンゴや白桃にバニラ・トーストの樽香。厚みとまろやかな酸のバランスで判断。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["イエロー", "黄金色がかった"], intensity: ["やや濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["よく熟した", "成熟度が高い"],
      aromaFirst: ["しっかりと感じられる", "強い"],
      aromaFruit: ["リンゴ", "洋梨", "白桃", "アカシア"],
      aromaSpice: ["バニラ", "トースト"],
      aromaImpression: ["芳醇な", "樽からのニュアンス"],
      attack: ["やや強い"], sweetness: ["まろやかな"], acidity: ["なめらかな"], bitterness: ["コク（深み）を与える"],
      balance: ["まろやかな", "厚みのある"], alcohol: ["やや強め"], finish: ["やや長い"],
      evaluation: ["成熟度が高く豊かな"], temperature: ["11～14度"], glass: ["中庸"],
      vintage: ["2022年"], country: ["フランス"], grape: ["シャルドネ"],
    },
  },
  {
    id: "rs-de",
    color: "white",
    label: "白ワイン C",
    name: "リースリング（ドイツ 2022）",
    note: "白い花・柑橘にペトロール香。豊かな酸と残糖のバランスが決め手。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "レモンイエロー"], intensity: ["淡い"], viscosity: ["やや軽い"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["しっかりと感じられる", "華やかな"],
      aromaFruit: ["柑橘類", "青リンゴ", "白桃", "スイカズラ"],
      aromaSpice: ["ペトロール", "蜂蜜"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["やや軽い"], sweetness: ["残糖がある"], acidity: ["シャープな"], bitterness: ["控えめ"],
      balance: ["溌剌とした", "ジューシーな"], alcohol: ["やや軽め"], finish: ["やや長い"],
      evaluation: ["シンプル、フレッシュ感を楽しむ"], temperature: ["8～10度"], glass: ["小ぶり"],
      vintage: ["2022年"], country: ["ドイツ"], grape: ["リースリング"],
    },
  },
  {
    id: "koshu-jp",
    color: "white",
    label: "白ワイン D",
    name: "甲州（日本 2023）",
    note: "控えめでニュートラルな香り、柑橘と和柑橘の内皮の苦味。淡い外観と穏やかな味わい。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "レモンイエロー"], intensity: ["無色に近い"], viscosity: ["さらっとした"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["控えめ", "閉じている"],
      aromaFruit: ["柑橘類", "青リンゴ", "洋梨", "白バラ"],
      aromaSpice: ["硫黄", "杏仁豆腐"],
      aromaImpression: ["若々しい", "ニュートラルな"],
      attack: ["軽い"], sweetness: ["弱い"], acidity: ["爽やかな"], bitterness: ["穏やかな"],
      balance: ["スリムな", "ドライな"], alcohol: ["やや軽め"], finish: ["やや短い"],
      evaluation: ["シンプル、フレッシュ感を楽しむ"], temperature: ["8～10度"], glass: ["小ぶり"],
      vintage: ["2023年"], country: ["日本"], grape: ["甲州"],
    },
  },
  {
    id: "gw-fr",
    color: "white",
    label: "白ワイン E",
    name: "ゲヴュルツトラミネール（フランス 2022）",
    note: "ライチ・バラの華やかなアロマ。おだやかな酸とやや高いアルコールのボリューム感。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["イエロー", "黄金色がかった"], intensity: ["やや濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["よく熟した", "成熟度が高い"],
      aromaFirst: ["強い", "華やかな"],
      aromaFruit: ["ライチ", "白バラ", "マンゴー", "キンモクセイ"],
      aromaSpice: ["コリアンダー", "蜂蜜"],
      aromaImpression: ["華やかな", "第1アロマが強い"],
      attack: ["やや強い"], sweetness: ["豊かな"], acidity: ["おだやかな"], bitterness: ["穏やかな"],
      balance: ["まろやかな", "豊満な"], alcohol: ["やや強め"], finish: ["やや長い"],
      evaluation: ["成熟度が高く豊かな"], temperature: ["8～10度"], glass: ["中庸"],
      vintage: ["2022年"], country: ["フランス"], grape: ["ゲヴュルツトラミネール"],
    },
  },
  {
    id: "pn-fr",
    color: "red",
    label: "赤ワイン A",
    name: "ピノ・ノワール（フランス 2021）",
    note: "明るいルビー色と赤系果実。なめらかな酸とサラサラしたタンニンのエレガント系。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ルビー", "紫がかった"], intensity: ["やや明るい"], viscosity: ["やや軽い"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["控えめ", "華やかな"],
      aromaFruit: ["イチゴ", "ラズベリー", "バラ", "紅茶"],
      aromaSpice: ["シナモン", "土"],
      aromaImpression: ["華やかな", "第1アロマが強い"],
      attack: ["やや軽い"], sweetness: ["弱い"], acidity: ["爽やかな"], tannin: ["サラサラとした"],
      balance: ["スマートな", "流れるような"], alcohol: ["中程度"], finish: ["やや長い"],
      evaluation: ["エレガントで余韻の長い"], temperature: ["15～18度"], glass: ["大ぶり"], decant: ["必要なし"],
      vintage: ["2021年"], country: ["フランス"], grape: ["ピノ・ノワール"],
    },
  },
  {
    id: "cs-us",
    color: "red",
    label: "赤ワイン B",
    name: "カベルネ・ソーヴィニヨン（アメリカ 2021）",
    note: "濃いダークチェリーレッド、カシスと樽香。力強いタンニンと厚みのあるボディ。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ダークチェリーレッド", "黒みを帯びた"], intensity: ["濃い"], viscosity: ["強い"],
      appearanceImpression: ["よく熟した", "濃縮感がある"],
      aromaFirst: ["しっかりと感じられる", "強い"],
      aromaFruit: ["カシス", "ブラックチェリー", "ブラックベリー", "ユーカリ"],
      aromaSpice: ["バニラ", "ロースト"],
      aromaImpression: ["芳醇な", "樽からのニュアンス"],
      attack: ["強い"], sweetness: ["豊かな"], acidity: ["なめらかな"], tannin: ["力強い"],
      balance: ["骨格のしっかりした", "肉厚な"], alcohol: ["やや強め"], finish: ["長い"],
      evaluation: ["濃縮し力強い"], temperature: ["15～18度"], glass: ["大ぶり"], decant: ["事前に（30分以上前）"],
      vintage: ["2021年"], country: ["アメリカ"], grape: ["カベルネ・ソーヴィニヨン"],
    },
  },
  {
    id: "sy-au",
    color: "red",
    label: "赤ワイン C",
    name: "シラーズ（オーストラリア 2021）",
    note: "黒コショウとチョコレートのニュアンス。濃い外観と豊満で力強い味わい。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ダークチェリーレッド", "紫がかった"], intensity: ["濃い"], viscosity: ["強い"],
      appearanceImpression: ["よく熟した", "濃縮感がある"],
      aromaFirst: ["しっかりと感じられる", "強い"],
      aromaFruit: ["ブラックベリー", "干しプラム", "ブルーベリー", "スミレ"],
      aromaSpice: ["黒コショウ", "チョコレート"],
      aromaImpression: ["芳醇な", "樽からのニュアンス"],
      attack: ["強い"], sweetness: ["豊かな"], acidity: ["やわらかな"], tannin: ["力強い"],
      balance: ["肉厚な", "力強い"], alcohol: ["やや強め"], finish: ["長い"],
      evaluation: ["濃縮し力強い"], temperature: ["15～18度"], glass: ["大ぶり"], decant: ["事前に（30分以上前）"],
      vintage: ["2021年"], country: ["オーストラリア"], grape: ["シラー（シラーズ）"],
    },
  },
  {
    id: "sg-it",
    color: "red",
    label: "赤ワイン D",
    name: "サンジョヴェーゼ（イタリア 2021）",
    note: "ルビー～ガーネット、赤系果実とドライハーブ。しっかりした酸と収斂性のあるタンニン。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ルビー", "ガーネット"], intensity: ["やや濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["よく熟した", "濃縮感がある"],
      aromaFirst: ["しっかりと感じられる", "開いている"],
      aromaFruit: ["ラズベリー", "ブラックチェリー", "干しプラム", "紅茶"],
      aromaSpice: ["甘草", "土"],
      aromaImpression: ["芳醇な", "熟成感が現れている"],
      attack: ["やや強い"], sweetness: ["まろやかな"], acidity: ["シャープな"], tannin: ["収斂性のある"],
      balance: ["固い", "骨格のしっかりした"], alcohol: ["中程度"], finish: ["やや長い"],
      evaluation: ["成熟度が高く豊かな"], temperature: ["15～18度"], glass: ["中庸"], decant: ["必要なし"],
      vintage: ["2021年"], country: ["イタリア"], grape: ["サンジョヴェーゼ"],
    },
  },
  {
    id: "mba-jp",
    color: "red",
    label: "赤ワイン E",
    name: "マスカット・ベーリーA（日本 2022）",
    note: "イチゴキャンディのような甘い香り。明るい色調、軽快でサラサラしたタンニン。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ルビー", "紫がかった"], intensity: ["明るい"], viscosity: ["やや軽い"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["開いている", "華やかな"],
      aromaFruit: ["イチゴ", "ラズベリー", "バラ", "ゼラニウム"],
      aromaSpice: ["甘草", "シナモン"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["軽い"], sweetness: ["まろやかな"], acidity: ["爽やかな"], tannin: ["サラサラとした"],
      balance: ["スマートな", "流れるような"], alcohol: ["やや軽め"], finish: ["やや短い"],
      evaluation: ["シンプル、フレッシュ感を楽しむ"], temperature: ["11～14度"], glass: ["中庸"], decant: ["必要なし"],
      vintage: ["2022年"], country: ["日本"], grape: ["マスカット・ベーリーA"],
    },
  },
];

// ------------------------------------------------------------
// 主要品種フラッシュカード データ
// front: 品種名 / back: 特徴（外観・香り・味わい・決め手・主産地）
// ------------------------------------------------------------
const GRAPES = [
  // ---- 白 ----
  { name: "シャルドネ", color: "white",
    appearance: "産地・樽の有無で幅広い。樽熟成は黄金色がかったイエロー、粘性やや強い",
    aroma: "リンゴ、洋梨、白桃。樽由来のバニラ・トースト・バター",
    taste: "まろやかな酸、厚みのあるボディ",
    key: "品種特有の香りが少なく「樽・乳製品」のニュアンスで判断。冷涼産地（シャブリ等）はミネラルと高い酸",
    region: "フランス（ブルゴーニュ）、アメリカ、オーストラリア" },
  { name: "ソーヴィニヨン・ブラン", color: "white",
    appearance: "グリーンがかった淡いレモンイエロー",
    aroma: "柑橘類、ハーブ、切りたての芝生。NZはパッションフルーツが顕著",
    taste: "シャープな酸、フレッシュでドライ",
    key: "ハーブ・草の香り＋高い酸。NZ産はトロピカル寄り",
    region: "フランス（ロワール）、ニュージーランド、チリ" },
  { name: "リースリング", color: "white",
    appearance: "グリーンがかった淡いレモンイエロー",
    aroma: "白い花、柑橘、青リンゴ。熟成でペトロール（灯油）香",
    taste: "鋭い酸と残糖のバランス。アルコール低め（独）",
    key: "残糖＋高い酸＋ペトロール香の三点セット",
    region: "ドイツ、フランス（アルザス）、オーストラリア" },
  { name: "甲州", color: "white",
    appearance: "無色に近いほど淡い",
    aroma: "控えめな柑橘・白い花。ニュートラル",
    taste: "穏やかで軽く、後味に柑橘の内皮のような苦味",
    key: "香りの弱さ・外観の淡さ・低めのアルコール",
    region: "日本（山梨）" },
  { name: "ゲヴュルツトラミネール", color: "white",
    appearance: "やや濃いイエロー",
    aroma: "ライチ、バラ、白い花、スパイス",
    taste: "酸はおだやか、アルコールのボリューム感",
    key: "ライチの華やかなアロマ＋低い酸＋高アルコール",
    region: "フランス（アルザス）、ドイツ" },
  { name: "ミュスカデ", color: "white",
    appearance: "グリーンがかった淡い色調",
    aroma: "控えめな柑橘・青リンゴ。シュール・リー由来の酵母香",
    taste: "軽快でドライ、フレッシュな酸",
    key: "全体の軽さとニュートラルさ。甲州との識別は酵母ニュアンス",
    region: "フランス（ロワール）" },
  { name: "シュナン・ブラン", color: "white",
    appearance: "中程度のイエロー",
    aroma: "カリン、蜂蜜、白い花",
    taste: "豊かな酸。辛口〜甘口までタイプが幅広い",
    key: "蜂蜜・カリン香と高い酸の共存",
    region: "フランス（ロワール）、南アフリカ" },
  { name: "ヴィオニエ", color: "white",
    appearance: "やや濃いイエロー",
    aroma: "アプリコット、白桃、白い花",
    taste: "酸は穏やか、豊満で高アルコール",
    key: "アプリコット香＋低酸のボリューム感（ゲヴュルツと迷ったらライチの有無）",
    region: "フランス（ローヌ北部）" },
  { name: "アルバリーニョ", color: "white",
    appearance: "淡いレモンイエロー",
    aroma: "柑橘、白桃、潮風・ミネラル",
    taste: "爽やかな酸、ほのかな塩味と苦味",
    key: "海を思わせる塩気のニュアンス",
    region: "スペイン（リアス・バイシャス）" },
  { name: "トロンテス", color: "white",
    appearance: "淡い〜中程度のイエロー",
    aroma: "マスカット、白い花、ライチ系の華やかさ",
    taste: "辛口で酸は中程度",
    key: "華やかなアロマなのに辛口。ゲヴュルツより酸が高い",
    region: "アルゼンチン" },
  // ---- 赤 ----
  { name: "ピノ・ノワール", color: "red",
    appearance: "明るいルビー、エッジは淡い",
    aroma: "イチゴ、ラズベリー、バラ、土・紅茶",
    taste: "なめらかな酸、サラサラとしたタンニン",
    key: "淡い色調＋赤系果実＋シルキーな口当たり",
    region: "フランス（ブルゴーニュ）、ニュージーランド、アメリカ" },
  { name: "カベルネ・ソーヴィニヨン", color: "red",
    appearance: "濃いダークチェリーレッド、黒みを帯びる",
    aroma: "カシス、杉、冷涼産地はピーマン。樽のバニラ・ロースト",
    taste: "力強いタンニン、しっかりした骨格",
    key: "濃い色＋カシス＋強いタンニン",
    region: "フランス（ボルドー）、アメリカ、チリ、オーストラリア" },
  { name: "メルロ", color: "red",
    appearance: "濃いめのダークチェリーレッド",
    aroma: "ブラックチェリー、プラム、土",
    taste: "タンニンは緻密でまろやか、ふくよかな果実味",
    key: "カベルネより柔らかく丸い印象",
    region: "フランス（ボルドー右岸）、日本（長野）" },
  { name: "シラー（シラーズ）", color: "red",
    appearance: "紫がかった濃い色調",
    aroma: "黒コショウ、ブラックベリー、スミレ。豪はチョコレート",
    taste: "豊満で力強い、豊かなタンニン",
    key: "黒コショウのスパイス香",
    region: "フランス（ローヌ北部）、オーストラリア" },
  { name: "サンジョヴェーゼ", color: "red",
    appearance: "ルビー〜ガーネット",
    aroma: "赤系果実、ドライハーブ、紅茶",
    taste: "高い酸＋収斂性のあるタンニン",
    key: "酸とタンニンの両方が強い",
    region: "イタリア（トスカーナ）" },
  { name: "テンプラニーリョ", color: "red",
    appearance: "中〜濃いルビー",
    aroma: "干しプラム、イチゴジャム、バニラ・ココナッツ（米国樽）",
    taste: "酸はまろやか、熟した果実味",
    key: "アメリカンオーク由来のバニラ・ココナッツ香",
    region: "スペイン（リオハ）" },
  { name: "ガメイ", color: "red",
    appearance: "紫がかった明るいルビー",
    aroma: "イチゴ、ラズベリー、バナナ・キャンディ（MC法）",
    taste: "軽快でフレッシュな酸、タンニン軽め",
    key: "キャンディ・バナナ香＋軽さ。MBAと迷ったら綿あめ香の強さ",
    region: "フランス（ボージョレ）" },
  { name: "グルナッシュ", color: "red",
    appearance: "やや明るいルビー、早くオレンジがかる",
    aroma: "イチゴジャム、干しプラム、甘いスパイス",
    taste: "酸は低め、高アルコール、甘やかな果実味",
    key: "色は淡めなのにアルコールが高い",
    region: "フランス（ローヌ南部）、スペイン（ガルナッチャ）" },
  { name: "ネッビオーロ", color: "red",
    appearance: "明るめのガーネット、縁はオレンジがかる",
    aroma: "バラ、タール、チェリー、なめし革",
    taste: "強烈なタンニンと高い酸",
    key: "淡い色と裏腹の強いタンニン・高い酸",
    region: "イタリア（ピエモンテ）" },
  { name: "ジンファンデル", color: "red",
    appearance: "中〜濃いルビー",
    aroma: "ブラックベリージャム、甘いスパイス",
    taste: "甘やかな果実味、高アルコール、タンニン中程度",
    key: "ジャムのような甘い果実味と高アルコール",
    region: "アメリカ（カリフォルニア）" },
  { name: "マスカット・ベーリーA", color: "red",
    appearance: "明るいルビー",
    aroma: "イチゴキャンディ、綿あめ",
    taste: "軽快、サラサラとしたタンニン",
    key: "綿あめ・キャンディ香（フラネオール）",
    region: "日本" },
];

// ------------------------------------------------------------
// 過去の出題品種データ（ワインエキスパート二次試験）
// 出典: ワイン受験.com「過去の出題ワインの品種と生産国」(2026-08時点で取得)
// https://www.wine-jyuken.com/second_exam/kakonosyutudai
// type: "white" | "red" | "other"（その他の酒類）
// ------------------------------------------------------------
const PAST_EXAMS = [
  { year: 2025, items: [
    { type: "white", name: "リースリング", country: "オーストラリア" },
    { type: "white", name: "ソーヴィニヨン・ブラン", country: "フランス" },
    { type: "red", name: "テンプラニーリョ", country: "スペイン" },
    { type: "red", name: "カルメネール", country: "チリ" },
    { type: "other", name: "スコッチ・ウイスキー" },
  ]},
  { year: 2024, items: [
    { type: "white", name: "ミュスカデ", country: "フランス" },
    { type: "white", name: "シャルドネ", country: "日本" },
    { type: "red", name: "カベルネ・ソーヴィニヨン", country: "アメリカ" },
    { type: "red", name: "サンジョヴェーゼ", country: "イタリア" },
    { type: "other", name: "バーボン・ウイスキー" },
  ]},
  { year: 2023, items: [
    { type: "white", name: "ソーヴィニヨン・ブラン", country: "チリ" },
    { type: "white", name: "リースリング", country: "オーストラリア" },
    { type: "red", name: "グルナッシュ", country: "フランス" },
    { type: "red", name: "テンプラニーリョ", country: "スペイン" },
    { type: "other", name: "ジン" },
  ]},
  { year: 2022, items: [
    { type: "white", name: "ソーヴィニヨン・ブラン", country: "ニュージーランド" },
    { type: "white", name: "甲州", country: "日本" },
    { type: "red", name: "カベルネ・ソーヴィニヨン", country: "アメリカ" },
    { type: "red", name: "シラー", country: "フランス" },
    { type: "other", name: "オー・ド・ヴィー・ド・キルシュ" },
  ]},
  { year: 2021, items: [
    { type: "white", name: "リースリング", country: "フランス" },
    { type: "white", name: "ヴィオニエ", country: "フランス" },
    { type: "red", name: "テンプラニーリョ", country: "スペイン" },
    { type: "red", name: "カベルネ・ソーヴィニヨン", country: "チリ" },
    { type: "other", name: "テキーラ" },
  ]},
  { year: 2020, items: [
    { type: "white", name: "トロンテス", country: "アルゼンチン" },
    { type: "white", name: "シャルドネ", country: "フランス" },
    { type: "red", name: "カベルネ・フラン", country: "フランス" },
    { type: "red", name: "ピノ・ノワール", country: "ニュージーランド" },
    { type: "other", name: "ラム" },
  ]},
  { year: 2019, items: [
    { type: "white", name: "ソーヴィニヨン・ブラン", country: "ニュージーランド" },
    { type: "white", name: "甲州", country: "日本" },
    { type: "red", name: "サンジョヴェーゼ", country: "イタリア" },
    { type: "red", name: "カベルネ・ソーヴィニヨン", country: "オーストラリア" },
    { type: "other", name: "紹興酒" },
  ]},
  { year: 2018, items: [
    { type: "white", name: "リースリング", country: "ドイツ" },
    { type: "white", name: "シャルドネ", country: "オーストラリア" },
    { type: "red", name: "メルロ", country: "日本" },
    { type: "red", name: "グルナッシュ", country: "フランス" },
    { type: "other", name: "ベネディクティン" },
  ]},
  { year: 2017, items: [
    { type: "white", name: "ソーヴィニヨン・ブラン", country: "チリ" },
    { type: "white", name: "ミュスカデ", country: "フランス" },
    { type: "red", name: "ガメイ", country: "フランス" },
    { type: "red", name: "マルベック", country: "アルゼンチン" },
    { type: "other", name: "サンブーカ" },
  ]},
  { year: 2016, items: [
    { type: "white", name: "リースリング", country: "フランス" },
    { type: "white", name: "シャルドネ", country: "アメリカ" },
    { type: "red", name: "シラー", country: "オーストラリア" },
    { type: "red", name: "テンプラニーリョ", country: "スペイン" },
    { type: "other", name: "泡盛" },
  ]},
  { year: 2015, items: [
    { type: "white", name: "リースリング", country: "オーストラリア" },
    { type: "white", name: "シャルドネ", country: "フランス" },
    { type: "red", name: "シラー", country: "フランス" },
    { type: "red", name: "カベルネ・ソーヴィニヨン", country: "アメリカ" },
    { type: "other", name: "コニャック" },
    { type: "other", name: "アマレット" },
  ]},
  { year: 2014, items: [
    { type: "white", name: "リースリング", country: "ドイツ" },
    { type: "white", name: "ソーヴィニヨン・ブラン", country: "ニュージーランド" },
    { type: "red", name: "ピノ・ノワール", country: "アメリカ" },
    { type: "red", name: "シラー", country: "フランス" },
    { type: "other", name: "シングルモルト・ウイスキー" },
    { type: "other", name: "ガリアーノ" },
  ]},
  { year: 2013, items: [
    { type: "white", name: "甲州", country: "日本" },
    { type: "white", name: "ソーヴィニヨン・ブラン", country: "フランス" },
    { type: "red", name: "カベルネ・フラン", country: "フランス" },
    { type: "red", name: "ピノ・ノワール", country: "アメリカ" },
    { type: "other", name: "カルヴァドス" },
    { type: "other", name: "トウニー・ポート" },
  ]},
  { year: 2012, items: [
    { type: "white", name: "リースリング", country: "オーストラリア" },
    { type: "white", name: "シャルドネ", country: "フランス" },
    { type: "red", name: "ガメイ", country: "フランス" },
    { type: "red", name: "ネッビオーロ", country: "イタリア" },
    { type: "other", name: "ホワイト・キュラソー（コアントロー）" },
    { type: "other", name: "カルヴァドス" },
  ]},
  { year: 2011, items: [
    { type: "white", name: "シャルドネ", country: "アメリカ" },
    { type: "white", name: "リースリング", country: "フランス" },
    { type: "red", name: "シラー", country: "オーストラリア" },
    { type: "red", name: "テンプラニーリョ", country: "スペイン" },
    { type: "other", name: "ドライ・ヴェルモット" },
    { type: "other", name: "ウォッカ" },
  ]},
];
