// ============================================================
// ワインエキスパート2次試験 テイスティングコメント練習 データ
// ------------------------------------------------------------
// ※ 用語・並び順はワイン受験.com「テイスティング解答用紙」
//    （2026年版, comment-sheet-w.pdf / comment-sheet-r.pdf）に準拠。
//    「選択数(pick)」は本番で年により指定が変わるため目安です。
//    terms / pick / 模範解答(answers) は自由に編集できます。
// ============================================================

const VOCAB = {
  white: [
    { id: "clarity",    group: "外観", title: "清澄度", pick: 1,
      terms: ["澄んだ", "やや濁った", "濁った"] },
    { id: "brightness", group: "外観", title: "輝き", pick: 1,
      terms: ["輝きのある", "ややくすんだ", "モヤがかかった"] },
    { id: "color",      group: "外観", title: "色調", pick: 2,
      terms: ["シルバーがかった", "グリーンがかった", "黄金色がかった",
              "レモンイエロー", "イエロー", "黄金色", "トパーズ", "オレンジ（グリ）を帯びた", "アンバー"] },
    { id: "intensity",  group: "外観", title: "濃淡", pick: 1,
      terms: ["無色に近い", "淡い", "やや濃い", "濃い", "非常に濃い"] },
    { id: "viscosity",  group: "外観", title: "粘性", pick: 1,
      terms: ["さらっとした", "適度な", "やや強い", "ねっとりとした"] },
    { id: "appearanceImpression", group: "外観", title: "外観の印象", pick: 2,
      terms: ["若々しい", "やや発展した", "熟成のニュアンスが見える", "熟成した", "酸化が進んだ",
              "軽快な", "成熟度が高い", "濃縮感がある", "気泡が見える", "発泡性"] },
    { id: "aromaFirst", group: "香り", title: "第一印象", pick: 2,
      terms: ["閉じている", "控えめ", "開いている", "力強い",
              "フレッシュな", "ミネラリー", "華やかな", "熟度の高い", "豊かな", "濃縮感がある", "セイボリーな", "複雑な"] },
    { id: "aromaFruit", group: "香り", title: "果実", pick: 3,
      terms: ["柑橘類", "青リンゴ", "リンゴ", "洋梨", "マスカット", "花梨", "パッションフルーツ",
              "白桃", "アプリコット", "パイナップル", "ライチ", "バナナ", "マンゴー"] },
    { id: "aromaFlora", group: "香り", title: "花・植物", pick: 2,
      terms: ["スイカズラ", "アカシア", "白バラ", "キンモクセイ", "菩提樹", "柑橘類の花",
              "ミント", "アニス", "ヴェルヴェーヌ", "ハーブ", "タイム",
              "フレッシュ・アーモンド", "ヘーゼルナッツ"] },
    { id: "aromaSpice", group: "香り", title: "香辛料・芳香・化学物質", pick: 2,
      terms: ["石灰", "火打石", "貝殻", "鉱物", "海の香り",
              "トースト", "ヴァニラ", "煙・燻製",
              "シナモン", "白胡椒", "コリアンダーシード", "丁子", "香木", "ジンジャーブレッド",
              "硫黄", "ペトロール（ケロセン）", "パン・ドゥ・ミ", "乳製品", "フェノール", "麝香",
              "花の蜜", "蜂蜜", "ワックス", "蜜蝋"] },
    { id: "aromaImpression", group: "香り", title: "香りの印象", pick: 2,
      terms: ["若々しい", "嫌気的な", "熟成感が現れている", "酸化熟成の段階にある",
              "第1アロマが強い", "第2アロマが強い", "ニュートラル", "木樽からのニュアンス", "成熟度が高い"] },
    { id: "attack",   group: "味わい", title: "アタック", pick: 1,
      terms: ["軽い", "やや軽い", "やや強い", "強い", "インパクトのある"] },
    { id: "sweetness", group: "味わい", title: "甘み（アルコールのボリューム感も含む）", pick: 1,
      terms: ["ドライ", "ソフトな", "まろやか", "豊かな", "残糖がある"] },
    { id: "acidity",  group: "味わい", title: "酸味", pick: 1,
      terms: ["なめらかな", "軽やかな", "爽やかな", "はつらつとした", "力強い", "直線的", "堅固な"] },
    { id: "bitterness", group: "味わい", title: "苦味", pick: 1,
      terms: ["控えめ", "穏やかな", "コク(深み)を与える", "旨味をともなった", "強い(突出した)"] },
    { id: "balance",  group: "味わい", title: "バランス", pick: 2,
      terms: ["スムーズな", "コンパクトな", "スリムな", "ドライな", "抑制された",
              "ジューシーな", "豊潤な", "厚みのある", "まろやかな", "ねっとりした"] },
    { id: "alcohol",  group: "味わい", title: "アルコール", pick: 1,
      terms: ["11%未満", "11%～12%未満", "12%～13%未満", "13%～14%未満", "14%以上"] },
    { id: "finish",   group: "味わい", title: "余韻", pick: 1,
      terms: ["短い", "やや短い", "やや長い", "長い"] },
    { id: "evaluation", group: "総合評価", title: "評価", pick: 1,
      terms: ["シンプル、フレッシュ感を楽しむ", "エレガントで、ミネラリー", "滑らかで、バランスが良い",
              "成熟度が高く、豊かな", "濃縮し、力強い", "ポテンシャルの高い"] },
    { id: "temperature", group: "総合評価", title: "適正温度", pick: 1,
      terms: ["8度未満", "8～10度", "11～14度", "15～18度", "19度以上"] },
    { id: "glass",    group: "総合評価", title: "グラス", pick: 1,
      terms: ["小ぶり", "中庸", "大ぶり", "バルーン型", "チューリップ型"] },
    { id: "vintage",  group: "結論", title: "収穫年", pick: 1,
      terms: ["2019年", "2020年", "2021年", "2022年", "2023年", "2024年"] },
    { id: "country",  group: "結論", title: "生産地", pick: 1,
      terms: ["フランス", "イタリア", "スペイン", "ドイツ", "オーストリア", "アメリカ",
              "オーストラリア", "ニュージーランド", "チリ", "アルゼンチン", "南アフリカ", "日本"] },
    { id: "grape",    group: "結論", title: "主なブドウ品種", pick: 1,
      terms: ["シャルドネ", "ソーヴィニヨン・ブラン", "リースリング", "甲州", "ゲヴュルツトラミネール",
              "ミュスカデ", "シュナン・ブラン", "ヴィオニエ", "アルバリーニョ", "トロンテス", "ピノ・グリージョ"] },
  ],

  red: [
    { id: "clarity",    group: "外観", title: "清澄度", pick: 1,
      terms: ["澄んだ", "深みのある", "やや濁った", "濁った"] },
    { id: "brightness", group: "外観", title: "輝き", pick: 1,
      terms: ["輝きのある", "艶のある", "モヤがかった"] },
    { id: "color",      group: "外観", title: "色調", pick: 2,
      terms: ["紫がかった", "オレンジがかった", "黒みを帯びた", "縁が明るい",
              "ルビー", "ラズベリーレッド", "ガーネット", "ダークチェリーレッド", "トパーズ", "マホガニー", "レンガ"] },
    { id: "intensity",  group: "外観", title: "濃淡", pick: 1,
      terms: ["淡い", "明るい", "やや明るい", "やや濃い", "濃い", "非常に濃い"] },
    { id: "viscosity",  group: "外観", title: "粘性", pick: 1,
      terms: ["さらっとした", "やや軽い", "やや強い", "強い"] },
    { id: "appearanceImpression", group: "外観", title: "外観の印象", pick: 2,
      terms: ["若々しい", "若い状態を抜けた", "やや熟成した", "熟成した", "酸化熟成のニュアンス", "酸化が進んだ",
              "軽快な", "成熟度が高い", "濃縮感が強い"] },
    { id: "aromaFirst", group: "香り", title: "第一印象", pick: 2,
      terms: ["閉じている", "控えめ", "開いている", "強い",
              "ミネラリー", "華やかな", "濃縮感がある", "深みのある", "複雑な"] },
    { id: "aromaFruit", group: "香り", title: "果実", pick: 3,
      terms: ["イチゴ", "ラズベリー", "ブルーベリー", "カシス", "ブラックベリー", "ブラックチェリー",
              "干しプラム", "乾燥イチジク"] },
    { id: "aromaFlora", group: "香り", title: "花・植物", pick: 2,
      terms: ["バラ", "スミレ", "牡丹", "ゼラニウム",
              "ピーマン", "トマト", "黒オリーブ", "メントール", "シダ", "ローリエ", "杉", "針葉樹", "ユーカリ",
              "ドライハーブ", "タバコ", "紅茶", "スーボア",
              "キノコ", "トリュフ", "土"] },
    { id: "aromaSpice", group: "香り", title: "香辛料・芳香・化学物質", pick: 2,
      terms: ["黒胡椒", "丁子", "シナモン", "ナツメグ", "甘草",
              "ヴァニラ", "ロースト", "コーヒー", "チョコレート", "煙・燻製",
              "動物的なニュアンス", "鉄分", "生肉", "グリエ", "乾いた肉", "なめし皮",
              "樹脂", "ヨード", "ランシオ"] },
    { id: "aromaImpression", group: "香り", title: "香りの印象", pick: 2,
      terms: ["若々しい", "嫌気的な", "熟成感が現れている", "酸化熟成の段階にある", "酸化した",
              "第1アロマが強い", "第2アロマが強い", "ニュートラル", "木樽からのニュアンス"] },
    { id: "attack",   group: "味わい", title: "アタック", pick: 1,
      terms: ["軽い", "やや軽い", "やや強い", "強い", "インパクトのある"] },
    { id: "sweetness", group: "味わい", title: "甘み（アルコールのボリューム感も含む）", pick: 1,
      terms: ["ドライ", "ソフトな", "まろやか", "豊かな", "残糖がある"] },
    { id: "acidity",  group: "味わい", title: "酸味", pick: 1,
      terms: ["なめらかな", "軽やかな", "爽やかな", "生き生きとした", "しなやかな", "力強い", "直線的", "堅固な"] },
    { id: "tannin",   group: "味わい", title: "タンニン分", pick: 1,
      terms: ["サラサラとした", "シルキーな", "ヴィロードのような", "溶け込んだ", "緻密", "力強い", "収斂性のある"] },
    { id: "balance",  group: "味わい", title: "バランス", pick: 2,
      terms: ["スマートな", "骨格のしっかりした", "堅固な", "痩せた、渇いた",
              "ジューシーな", "豊満な", "力強い", "流れるような", "ふくよかな"] },
    { id: "alcohol",  group: "味わい", title: "アルコール", pick: 1,
      terms: ["11%未満", "11%～12%未満", "12%～13%未満", "13%～14%未満", "14%以上"] },
    { id: "finish",   group: "味わい", title: "余韻", pick: 1,
      terms: ["短い", "やや短い", "やや長い", "長い"] },
    { id: "evaluation", group: "総合評価", title: "評価", pick: 1,
      terms: ["シンプル、フレッシュ感を楽しむ", "エレガントで、余韻の長い", "複雑性があり、引き締まった",
              "成熟度が高く、豊か", "濃縮し、力強い"] },
    { id: "temperature", group: "総合評価", title: "適正温度", pick: 1,
      terms: ["10度未満", "10～13度", "14～16度", "17～20度", "21度以上"] },
    { id: "glass",    group: "総合評価", title: "グラス", pick: 1,
      terms: ["小ぶり", "中庸", "大ぶり", "バルーン型", "チューリップ型"] },
    { id: "vintage",  group: "結論", title: "収穫年", pick: 1,
      terms: ["2018年", "2019年", "2020年", "2021年", "2022年", "2023年"] },
    { id: "country",  group: "結論", title: "生産地", pick: 1,
      terms: ["フランス", "イタリア", "スペイン", "ドイツ", "アメリカ", "オーストラリア",
              "ニュージーランド", "チリ", "アルゼンチン", "南アフリカ", "日本"] },
    { id: "grape",    group: "結論", title: "主なブドウ品種", pick: 1,
      terms: ["ピノ・ノワール", "カベルネ・ソーヴィニヨン", "メルロ", "シラー（シラーズ）", "サンジョヴェーゼ",
              "テンプラニーリョ", "ガメイ", "グルナッシュ", "ネッビオーロ", "ジンファンデル", "マスカット・ベーリーA",
              "カベルネ・フラン", "マルベック", "カルメネール", "ピノタージュ"] },
  ],
};

// ------------------------------------------------------------
// 模範解答つきワインリスト
// answers のキーは上の VOCAB の id に対応。値は「選ぶべき用語」の配列。
// ------------------------------------------------------------
const WINES = [
  {
    id: "sb-nz",
    color: "white",
    label: "白ワイン A",
    name: "ソーヴィニヨン・ブラン（ニュージーランド 2023）",
    note: "ハーブと柑橘、パッションフルーツの香りが特徴。はつらつとした酸とフレッシュ感が決め手。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "レモンイエロー"], intensity: ["淡い"], viscosity: ["さらっとした"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["開いている", "フレッシュな"],
      aromaFruit: ["柑橘類", "青リンゴ", "パッションフルーツ"],
      aromaFlora: ["ハーブ", "ミント"],
      aromaSpice: ["火打石", "硫黄"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["やや軽い"], sweetness: ["ドライ"], acidity: ["はつらつとした"], bitterness: ["控えめ"],
      balance: ["スリムな", "ドライな"], alcohol: ["12%～13%未満"], finish: ["やや長い"],
      evaluation: ["シンプル、フレッシュ感を楽しむ"], temperature: ["8～10度"], glass: ["小ぶり"],
      vintage: ["2023年"], country: ["ニュージーランド"], grape: ["ソーヴィニヨン・ブラン"],
    },
  },
  {
    id: "ch-fr",
    color: "white",
    label: "白ワイン B",
    name: "シャルドネ（フランス 2022・樽熟成）",
    note: "熟したリンゴや白桃にヴァニラ・トーストの樽香。厚みとまろやかな酸のバランスで判断。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["黄金色がかった", "イエロー"], intensity: ["やや濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["成熟度が高い", "濃縮感がある"],
      aromaFirst: ["開いている", "豊かな"],
      aromaFruit: ["リンゴ", "洋梨", "白桃"],
      aromaFlora: ["アカシア", "ヘーゼルナッツ"],
      aromaSpice: ["トースト", "ヴァニラ"],
      aromaImpression: ["木樽からのニュアンス", "成熟度が高い"],
      attack: ["やや強い"], sweetness: ["まろやか"], acidity: ["なめらかな"], bitterness: ["コク(深み)を与える"],
      balance: ["厚みのある", "まろやかな"], alcohol: ["13%～14%未満"], finish: ["やや長い"],
      evaluation: ["成熟度が高く、豊かな"], temperature: ["11～14度"], glass: ["中庸"],
      vintage: ["2022年"], country: ["フランス"], grape: ["シャルドネ"],
    },
  },
  {
    id: "rs-de",
    color: "white",
    label: "白ワイン C",
    name: "リースリング（ドイツ 2022）",
    note: "白い花・柑橘にペトロール香。豊かな酸と残糖のバランスが決め手。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "レモンイエロー"], intensity: ["淡い"], viscosity: ["さらっとした"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["開いている", "華やかな"],
      aromaFruit: ["柑橘類", "青リンゴ", "白桃"],
      aromaFlora: ["スイカズラ", "菩提樹"],
      aromaSpice: ["ペトロール（ケロセン）", "蜂蜜"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["軽い"], sweetness: ["残糖がある"], acidity: ["はつらつとした"], bitterness: ["控えめ"],
      balance: ["スリムな", "ジューシーな"], alcohol: ["11%未満"], finish: ["やや長い"],
      evaluation: ["エレガントで、ミネラリー"], temperature: ["8～10度"], glass: ["小ぶり"],
      vintage: ["2022年"], country: ["ドイツ"], grape: ["リースリング"],
    },
  },
  {
    id: "koshu-jp",
    color: "white",
    label: "白ワイン D",
    name: "甲州（日本 2023）",
    note: "控えめでニュートラルな香り、柑橘の内皮のような苦味。淡い外観と穏やかな味わい。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "レモンイエロー"], intensity: ["無色に近い"], viscosity: ["さらっとした"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["控えめ", "フレッシュな"],
      aromaFruit: ["柑橘類", "青リンゴ", "洋梨"],
      aromaFlora: ["柑橘類の花", "ハーブ"],
      aromaSpice: ["硫黄", "石灰"],
      aromaImpression: ["若々しい", "ニュートラル"],
      attack: ["軽い"], sweetness: ["ドライ"], acidity: ["爽やかな"], bitterness: ["穏やかな"],
      balance: ["スリムな", "ドライな"], alcohol: ["11%～12%未満"], finish: ["やや短い"],
      evaluation: ["シンプル、フレッシュ感を楽しむ"], temperature: ["8～10度"], glass: ["小ぶり"],
      vintage: ["2023年"], country: ["日本"], grape: ["甲州"],
    },
  },
  {
    id: "gw-fr",
    color: "white",
    label: "白ワイン E",
    name: "ゲヴュルツトラミネール（フランス 2022）",
    note: "ライチ・バラの華やかなアロマ。穏やかな酸と高いアルコールのボリューム感。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["黄金色がかった", "イエロー"], intensity: ["やや濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["成熟度が高い", "濃縮感がある"],
      aromaFirst: ["開いている", "華やかな"],
      aromaFruit: ["ライチ", "マンゴー", "白桃"],
      aromaFlora: ["白バラ", "キンモクセイ"],
      aromaSpice: ["コリアンダーシード", "蜂蜜"],
      aromaImpression: ["第1アロマが強い", "成熟度が高い"],
      attack: ["やや強い"], sweetness: ["豊かな"], acidity: ["なめらかな"], bitterness: ["穏やかな"],
      balance: ["豊潤な", "まろやかな"], alcohol: ["14%以上"], finish: ["やや長い"],
      evaluation: ["成熟度が高く、豊かな"], temperature: ["8～10度"], glass: ["中庸"],
      vintage: ["2022年"], country: ["フランス"], grape: ["ゲヴュルツトラミネール"],
    },
  },
  {
    id: "pn-fr",
    color: "red",
    label: "赤ワイン A",
    name: "ピノ・ノワール（フランス 2021）",
    note: "明るいルビー色と赤系果実。生き生きとした酸とサラサラしたタンニンのエレガント系。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ルビー", "縁が明るい"], intensity: ["やや明るい"], viscosity: ["やや軽い"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["開いている", "華やかな"],
      aromaFruit: ["イチゴ", "ラズベリー", "ブラックチェリー"],
      aromaFlora: ["バラ", "紅茶"],
      aromaSpice: ["シナモン", "丁子"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["やや軽い"], sweetness: ["ドライ"], acidity: ["生き生きとした"], tannin: ["サラサラとした"],
      balance: ["スマートな", "流れるような"], alcohol: ["13%～14%未満"], finish: ["やや長い"],
      evaluation: ["エレガントで、余韻の長い"], temperature: ["14～16度"], glass: ["バルーン型"],
      vintage: ["2021年"], country: ["フランス"], grape: ["ピノ・ノワール"],
    },
  },
  {
    id: "cs-us",
    color: "red",
    label: "赤ワイン B",
    name: "カベルネ・ソーヴィニヨン（アメリカ 2021）",
    note: "黒みを帯びた濃い色調、カシスと樽香。力強いタンニンと骨格のしっかりしたボディ。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["黒みを帯びた", "ダークチェリーレッド"], intensity: ["濃い"], viscosity: ["強い"],
      appearanceImpression: ["成熟度が高い", "濃縮感が強い"],
      aromaFirst: ["強い", "濃縮感がある"],
      aromaFruit: ["カシス", "ブラックチェリー", "ブラックベリー"],
      aromaFlora: ["ユーカリ", "杉"],
      aromaSpice: ["ヴァニラ", "ロースト"],
      aromaImpression: ["若々しい", "木樽からのニュアンス"],
      attack: ["強い"], sweetness: ["豊かな"], acidity: ["なめらかな"], tannin: ["力強い"],
      balance: ["骨格のしっかりした", "豊満な"], alcohol: ["14%以上"], finish: ["長い"],
      evaluation: ["濃縮し、力強い"], temperature: ["17～20度"], glass: ["大ぶり"],
      vintage: ["2021年"], country: ["アメリカ"], grape: ["カベルネ・ソーヴィニヨン"],
    },
  },
  {
    id: "sy-au",
    color: "red",
    label: "赤ワイン C",
    name: "シラーズ（オーストラリア 2021）",
    note: "黒胡椒とチョコレートのニュアンス。濃い外観と豊満で力強い味わい。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["紫がかった", "ダークチェリーレッド"], intensity: ["濃い"], viscosity: ["強い"],
      appearanceImpression: ["成熟度が高い", "濃縮感が強い"],
      aromaFirst: ["強い", "濃縮感がある"],
      aromaFruit: ["ブラックベリー", "ブルーベリー", "干しプラム"],
      aromaFlora: ["スミレ", "ユーカリ"],
      aromaSpice: ["黒胡椒", "チョコレート"],
      aromaImpression: ["若々しい", "木樽からのニュアンス"],
      attack: ["強い"], sweetness: ["豊かな"], acidity: ["しなやかな"], tannin: ["力強い"],
      balance: ["豊満な", "力強い"], alcohol: ["14%以上"], finish: ["長い"],
      evaluation: ["濃縮し、力強い"], temperature: ["17～20度"], glass: ["大ぶり"],
      vintage: ["2021年"], country: ["オーストラリア"], grape: ["シラー（シラーズ）"],
    },
  },
  {
    id: "sg-it",
    color: "red",
    label: "赤ワイン D",
    name: "サンジョヴェーゼ（イタリア 2021）",
    note: "ルビー～ガーネット、赤系果実とドライハーブ。力強い酸と収斂性のあるタンニン。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ルビー", "ガーネット"], intensity: ["やや濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["若い状態を抜けた", "成熟度が高い"],
      aromaFirst: ["開いている", "複雑な"],
      aromaFruit: ["ラズベリー", "ブラックチェリー", "干しプラム"],
      aromaFlora: ["ドライハーブ", "紅茶"],
      aromaSpice: ["甘草", "なめし皮"],
      aromaImpression: ["熟成感が現れている", "第1アロマが強い"],
      attack: ["やや強い"], sweetness: ["ソフトな"], acidity: ["力強い"], tannin: ["収斂性のある"],
      balance: ["骨格のしっかりした", "堅固な"], alcohol: ["13%～14%未満"], finish: ["やや長い"],
      evaluation: ["複雑性があり、引き締まった"], temperature: ["17～20度"], glass: ["中庸"],
      vintage: ["2021年"], country: ["イタリア"], grape: ["サンジョヴェーゼ"],
    },
  },
  {
    id: "mba-jp",
    color: "red",
    label: "赤ワイン E",
    name: "マスカット・ベーリーA（日本 2022）",
    note: "イチゴキャンディのような甘い香り。明るい色調、軽快でサラサラしたタンニン。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["紫がかった", "ルビー"], intensity: ["明るい"], viscosity: ["やや軽い"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["開いている", "華やかな"],
      aromaFruit: ["イチゴ", "ラズベリー", "ブルーベリー"],
      aromaFlora: ["バラ", "ゼラニウム"],
      aromaSpice: ["甘草", "シナモン"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["軽い"], sweetness: ["ソフトな"], acidity: ["爽やかな"], tannin: ["サラサラとした"],
      balance: ["スマートな", "流れるような"], alcohol: ["11%～12%未満"], finish: ["やや短い"],
      evaluation: ["シンプル、フレッシュ感を楽しむ"], temperature: ["14～16度"], glass: ["中庸"],
      vintage: ["2022年"], country: ["日本"], grape: ["マスカット・ベーリーA"],
    },
  },
  {
    id: "sb-fr",
    color: "white",
    label: "白ワイン F",
    name: "ソーヴィニヨン・ブラン（フランス 2023）",
    note: "ロワール。NZより香りが控えめで、火打石のミネラルと直線的な酸が決め手。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "レモンイエロー"], intensity: ["淡い"], viscosity: ["さらっとした"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["控えめ", "ミネラリー"],
      aromaFruit: ["柑橘類", "青リンゴ", "洋梨"],
      aromaFlora: ["ハーブ", "ミント"],
      aromaSpice: ["火打石", "石灰"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["やや軽い"], sweetness: ["ドライ"], acidity: ["直線的"], bitterness: ["控えめ"],
      balance: ["スリムな", "ドライな"], alcohol: ["12%～13%未満"], finish: ["やや長い"],
      evaluation: ["エレガントで、ミネラリー"], temperature: ["8～10度"], glass: ["小ぶり"],
      vintage: ["2023年"], country: ["フランス"], grape: ["ソーヴィニヨン・ブラン"],
    },
  },
  {
    id: "ch-us",
    color: "white",
    label: "白ワイン G",
    name: "シャルドネ（アメリカ 2022）",
    note: "熟した白桃・パイナップルにバター・ヴァニラ。仏よりも豊満で酸なめらか、高アルコール。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["黄金色がかった", "イエロー"], intensity: ["やや濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["成熟度が高い", "濃縮感がある"],
      aromaFirst: ["開いている", "豊かな"],
      aromaFruit: ["白桃", "パイナップル", "洋梨"],
      aromaFlora: ["アカシア", "ヘーゼルナッツ"],
      aromaSpice: ["ヴァニラ", "乳製品"],
      aromaImpression: ["木樽からのニュアンス", "成熟度が高い"],
      attack: ["強い"], sweetness: ["豊かな"], acidity: ["なめらかな"], bitterness: ["コク(深み)を与える"],
      balance: ["厚みのある", "豊潤な"], alcohol: ["14%以上"], finish: ["やや長い"],
      evaluation: ["成熟度が高く、豊かな"], temperature: ["11～14度"], glass: ["中庸"],
      vintage: ["2022年"], country: ["アメリカ"], grape: ["シャルドネ"],
    },
  },
  {
    id: "rs-au",
    color: "white",
    label: "白ワイン H",
    name: "リースリング（オーストラリア 2022）",
    note: "ライムと直線的な酸の辛口。独との違いは残糖がなくアルコールがやや高いこと。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "レモンイエロー"], intensity: ["淡い"], viscosity: ["さらっとした"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["開いている", "フレッシュな"],
      aromaFruit: ["柑橘類", "青リンゴ", "白桃"],
      aromaFlora: ["柑橘類の花", "ミント"],
      aromaSpice: ["ペトロール（ケロセン）", "石灰"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["やや軽い"], sweetness: ["ドライ"], acidity: ["直線的"], bitterness: ["控えめ"],
      balance: ["スリムな", "ドライな"], alcohol: ["12%～13%未満"], finish: ["やや長い"],
      evaluation: ["エレガントで、ミネラリー"], temperature: ["8～10度"], glass: ["小ぶり"],
      vintage: ["2022年"], country: ["オーストラリア"], grape: ["リースリング"],
    },
  },
  {
    id: "pn-nz",
    color: "red",
    label: "赤ワイン F",
    name: "ピノ・ノワール（ニュージーランド 2021）",
    note: "仏より果実味が明るく濃いめ。チェリー系のジューシーさとシルキーなタンニン。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ルビー", "紫がかった"], intensity: ["やや明るい"], viscosity: ["やや強い"],
      appearanceImpression: ["若々しい", "成熟度が高い"],
      aromaFirst: ["開いている", "華やかな"],
      aromaFruit: ["ラズベリー", "ブラックチェリー", "ブルーベリー"],
      aromaFlora: ["スミレ", "紅茶"],
      aromaSpice: ["甘草", "ヴァニラ"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["やや強い"], sweetness: ["まろやか"], acidity: ["生き生きとした"], tannin: ["シルキーな"],
      balance: ["ジューシーな", "流れるような"], alcohol: ["13%～14%未満"], finish: ["やや長い"],
      evaluation: ["エレガントで、余韻の長い"], temperature: ["14～16度"], glass: ["バルーン型"],
      vintage: ["2021年"], country: ["ニュージーランド"], grape: ["ピノ・ノワール"],
    },
  },
  {
    id: "cs-cl",
    color: "red",
    label: "赤ワイン G",
    name: "カベルネ・ソーヴィニヨン（チリ 2021）",
    note: "米よりピーマン・ハーブのニュアンスが出やすい。果実味は充実、タンニンは緻密。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["黒みを帯びた", "ダークチェリーレッド"], intensity: ["濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["成熟度が高い", "濃縮感が強い"],
      aromaFirst: ["開いている", "濃縮感がある"],
      aromaFruit: ["カシス", "ブラックベリー", "ブラックチェリー"],
      aromaFlora: ["ピーマン", "ユーカリ"],
      aromaSpice: ["ヴァニラ", "ロースト"],
      aromaImpression: ["若々しい", "木樽からのニュアンス"],
      attack: ["やや強い"], sweetness: ["豊かな"], acidity: ["しなやかな"], tannin: ["緻密"],
      balance: ["骨格のしっかりした", "ジューシーな"], alcohol: ["14%以上"], finish: ["やや長い"],
      evaluation: ["濃縮し、力強い"], temperature: ["17～20度"], glass: ["大ぶり"],
      vintage: ["2021年"], country: ["チリ"], grape: ["カベルネ・ソーヴィニヨン"],
    },
  },
  {
    id: "sy-fr",
    color: "red",
    label: "赤ワイン H",
    name: "シラー（フランス 2021）",
    note: "ローヌ北部。黒胡椒と肉のニュアンス、豪シラーズより引き締まったスタイル。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["紫がかった", "ダークチェリーレッド"], intensity: ["濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["若々しい", "濃縮感が強い"],
      aromaFirst: ["開いている", "深みのある"],
      aromaFruit: ["ブラックベリー", "ブラックチェリー", "カシス"],
      aromaFlora: ["スミレ", "黒オリーブ"],
      aromaSpice: ["黒胡椒", "生肉"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["やや強い"], sweetness: ["まろやか"], acidity: ["しなやかな"], tannin: ["緻密"],
      balance: ["骨格のしっかりした", "力強い"], alcohol: ["13%～14%未満"], finish: ["やや長い"],
      evaluation: ["複雑性があり、引き締まった"], temperature: ["17～20度"], glass: ["大ぶり"],
      vintage: ["2021年"], country: ["フランス"], grape: ["シラー（シラーズ）"],
    },
  },
  {
    id: "tp-es",
    color: "red",
    label: "赤ワイン I",
    name: "テンプラニーリョ（スペイン 2021）",
    note: "過去15年で最頻出の赤。アメリカンオーク由来のヴァニラ・ココナッツと熟成ニュアンス。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ルビー", "ガーネット"], intensity: ["やや濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["若い状態を抜けた", "成熟度が高い"],
      aromaFirst: ["開いている", "複雑な"],
      aromaFruit: ["ラズベリー", "ブラックチェリー", "干しプラム"],
      aromaFlora: ["ドライハーブ", "タバコ"],
      aromaSpice: ["ヴァニラ", "なめし皮"],
      aromaImpression: ["熟成感が現れている", "木樽からのニュアンス"],
      attack: ["やや強い"], sweetness: ["まろやか"], acidity: ["なめらかな"], tannin: ["溶け込んだ"],
      balance: ["骨格のしっかりした", "ふくよかな"], alcohol: ["13%～14%未満"], finish: ["やや長い"],
      evaluation: ["成熟度が高く、豊か"], temperature: ["14～16度"], glass: ["中庸"],
      vintage: ["2021年"], country: ["スペイン"], grape: ["テンプラニーリョ"],
    },
  },
  {
    id: "ch-au", color: "white",
    name: "シャルドネ（オーストラリア 2022）",
    note: "2018年出題。果実味くっきり＋トースト。近年は酸を残した引き締まったスタイル。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "イエロー"], intensity: ["やや濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["若々しい", "成熟度が高い"],
      aromaFirst: ["開いている", "フレッシュな"],
      aromaFruit: ["白桃", "柑橘類", "リンゴ"],
      aromaFlora: ["アカシア", "フレッシュ・アーモンド"],
      aromaSpice: ["トースト", "火打石"],
      aromaImpression: ["若々しい", "木樽からのニュアンス"],
      attack: ["やや強い"], sweetness: ["まろやか"], acidity: ["はつらつとした"], bitterness: ["控えめ"],
      balance: ["ジューシーな", "厚みのある"], alcohol: ["13%～14%未満"], finish: ["やや長い"],
      evaluation: ["滑らかで、バランスが良い"], temperature: ["11～14度"], glass: ["中庸"],
      vintage: ["2022年"], country: ["オーストラリア"], grape: ["シャルドネ"],
    },
  },
  {
    id: "ch-jp", color: "white",
    name: "シャルドネ（日本 2023）",
    note: "2024年出題。穏やかな果実味と控えめな樽使い。すっきり上品。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "レモンイエロー"], intensity: ["淡い"], viscosity: ["適度な"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["控えめ", "フレッシュな"],
      aromaFruit: ["柑橘類", "リンゴ", "洋梨"],
      aromaFlora: ["アカシア", "柑橘類の花"],
      aromaSpice: ["硫黄", "乳製品"],
      aromaImpression: ["若々しい", "ニュートラル"],
      attack: ["やや軽い"], sweetness: ["ソフトな"], acidity: ["爽やかな"], bitterness: ["控えめ"],
      balance: ["スムーズな", "コンパクトな"], alcohol: ["12%～13%未満"], finish: ["やや短い"],
      evaluation: ["シンプル、フレッシュ感を楽しむ"], temperature: ["8～10度"], glass: ["中庸"],
      vintage: ["2023年"], country: ["日本"], grape: ["シャルドネ"],
    },
  },
  {
    id: "sb-cl", color: "white",
    name: "ソーヴィニヨン・ブラン（チリ 2023）",
    note: "2017・2023年出題。柑橘＋ややトロピカル。NZほど香りは強くない中間型。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "レモンイエロー"], intensity: ["淡い"], viscosity: ["さらっとした"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["開いている", "フレッシュな"],
      aromaFruit: ["柑橘類", "パッションフルーツ", "青リンゴ"],
      aromaFlora: ["ハーブ", "ミント"],
      aromaSpice: ["硫黄", "石灰"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["やや軽い"], sweetness: ["ドライ"], acidity: ["はつらつとした"], bitterness: ["控えめ"],
      balance: ["スリムな", "ジューシーな"], alcohol: ["12%～13%未満"], finish: ["やや短い"],
      evaluation: ["シンプル、フレッシュ感を楽しむ"], temperature: ["8～10度"], glass: ["小ぶり"],
      vintage: ["2023年"], country: ["チリ"], grape: ["ソーヴィニヨン・ブラン"],
    },
  },
  {
    id: "rs-fr", color: "white",
    name: "リースリング（フランス 2022）",
    note: "2016・2021年出題。アルザスは辛口で骨格しっかり、独より度数高め。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "レモンイエロー"], intensity: ["淡い"], viscosity: ["適度な"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["開いている", "ミネラリー"],
      aromaFruit: ["柑橘類", "青リンゴ", "洋梨"],
      aromaFlora: ["スイカズラ", "菩提樹"],
      aromaSpice: ["ペトロール（ケロセン）", "石灰"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["やや軽い"], sweetness: ["ドライ"], acidity: ["直線的"], bitterness: ["控えめ"],
      balance: ["ドライな", "スリムな"], alcohol: ["12%～13%未満"], finish: ["やや長い"],
      evaluation: ["エレガントで、ミネラリー"], temperature: ["8～10度"], glass: ["小ぶり"],
      vintage: ["2022年"], country: ["フランス"], grape: ["リースリング"],
    },
  },
  {
    id: "gw-de", color: "white",
    name: "ゲヴュルツトラミネール（ドイツ 2022）",
    note: "仏より軽やかで繊細。酸も比較的残る。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["レモンイエロー", "イエロー"], intensity: ["やや濃い"], viscosity: ["適度な"],
      appearanceImpression: ["若々しい", "成熟度が高い"],
      aromaFirst: ["開いている", "華やかな"],
      aromaFruit: ["ライチ", "白桃", "マスカット"],
      aromaFlora: ["白バラ", "キンモクセイ"],
      aromaSpice: ["コリアンダーシード", "花の蜜"],
      aromaImpression: ["第1アロマが強い", "若々しい"],
      attack: ["やや軽い"], sweetness: ["まろやか"], acidity: ["爽やかな"], bitterness: ["穏やかな"],
      balance: ["まろやかな", "ジューシーな"], alcohol: ["13%～14%未満"], finish: ["やや長い"],
      evaluation: ["成熟度が高く、豊かな"], temperature: ["8～10度"], glass: ["中庸"],
      vintage: ["2022年"], country: ["ドイツ"], grape: ["ゲヴュルツトラミネール"],
    },
  },
  {
    id: "ms-fr", color: "white",
    name: "ミュスカデ（フランス 2023）",
    note: "2017・2024年出題。軽快ドライ、シュール・リー由来の酵母（パン）ニュアンス。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "レモンイエロー"], intensity: ["無色に近い"], viscosity: ["さらっとした"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["控えめ", "フレッシュな"],
      aromaFruit: ["柑橘類", "青リンゴ", "洋梨"],
      aromaFlora: ["ハーブ", "柑橘類の花"],
      aromaSpice: ["パン・ドゥ・ミ", "石灰"],
      aromaImpression: ["若々しい", "ニュートラル"],
      attack: ["軽い"], sweetness: ["ドライ"], acidity: ["爽やかな"], bitterness: ["控えめ"],
      balance: ["スリムな", "ドライな"], alcohol: ["11%～12%未満"], finish: ["短い"],
      evaluation: ["シンプル、フレッシュ感を楽しむ"], temperature: ["8～10度"], glass: ["小ぶり"],
      vintage: ["2023年"], country: ["フランス"], grape: ["ミュスカデ"],
    },
  },
  {
    id: "vn-fr", color: "white",
    name: "ヴィオニエ（フランス 2022）",
    note: "2021年出題。アプリコットの華やかさ＋低酸のボリューム感。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["黄金色がかった", "イエロー"], intensity: ["やや濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["成熟度が高い", "濃縮感がある"],
      aromaFirst: ["開いている", "華やかな"],
      aromaFruit: ["アプリコット", "白桃", "花梨"],
      aromaFlora: ["アカシア", "スイカズラ"],
      aromaSpice: ["花の蜜", "蜂蜜"],
      aromaImpression: ["第1アロマが強い", "成熟度が高い"],
      attack: ["やや強い"], sweetness: ["豊かな"], acidity: ["なめらかな"], bitterness: ["穏やかな"],
      balance: ["豊潤な", "ねっとりした"], alcohol: ["14%以上"], finish: ["やや長い"],
      evaluation: ["成熟度が高く、豊かな"], temperature: ["11～14度"], glass: ["中庸"],
      vintage: ["2022年"], country: ["フランス"], grape: ["ヴィオニエ"],
    },
  },
  {
    id: "tr-ar", color: "white",
    name: "トロンテス（アルゼンチン 2023）",
    note: "2020年出題。マスカットの華やかなアロマなのに辛口。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "レモンイエロー"], intensity: ["淡い"], viscosity: ["適度な"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["開いている", "華やかな"],
      aromaFruit: ["マスカット", "ライチ", "柑橘類"],
      aromaFlora: ["白バラ", "キンモクセイ"],
      aromaSpice: ["花の蜜", "硫黄"],
      aromaImpression: ["第1アロマが強い", "若々しい"],
      attack: ["やや軽い"], sweetness: ["ドライ"], acidity: ["爽やかな"], bitterness: ["穏やかな"],
      balance: ["ドライな", "ジューシーな"], alcohol: ["13%～14%未満"], finish: ["やや短い"],
      evaluation: ["シンプル、フレッシュ感を楽しむ"], temperature: ["8～10度"], glass: ["小ぶり"],
      vintage: ["2023年"], country: ["アルゼンチン"], grape: ["トロンテス"],
    },
  },
  {
    id: "pg-it", color: "white",
    name: "ピノ・グリージョ（イタリア 2023）",
    note: "北東部。軽快・ドライ・ニュートラルで飲み口すっきり。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["レモンイエロー", "イエロー"], intensity: ["淡い"], viscosity: ["適度な"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["控えめ", "フレッシュな"],
      aromaFruit: ["洋梨", "柑橘類", "白桃"],
      aromaFlora: ["フレッシュ・アーモンド", "白バラ"],
      aromaSpice: ["石灰", "硫黄"],
      aromaImpression: ["若々しい", "ニュートラル"],
      attack: ["やや軽い"], sweetness: ["ドライ"], acidity: ["爽やかな"], bitterness: ["穏やかな"],
      balance: ["スムーズな", "ドライな"], alcohol: ["12%～13%未満"], finish: ["やや短い"],
      evaluation: ["シンプル、フレッシュ感を楽しむ"], temperature: ["8～10度"], glass: ["小ぶり"],
      vintage: ["2023年"], country: ["イタリア"], grape: ["ピノ・グリージョ"],
    },
  },
  {
    id: "pg-fr", color: "white",
    name: "ピノ・グリ（フランス 2022）",
    note: "アルザス。豊満で蜂蜜・スモークのニュアンス。伊のグリージョとの対比。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["黄金色がかった", "イエロー"], intensity: ["やや濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["成熟度が高い", "濃縮感がある"],
      aromaFirst: ["開いている", "豊かな"],
      aromaFruit: ["白桃", "アプリコット", "洋梨"],
      aromaFlora: ["アカシア", "ヘーゼルナッツ"],
      aromaSpice: ["蜂蜜", "煙・燻製"],
      aromaImpression: ["成熟度が高い", "第2アロマが強い"],
      attack: ["やや強い"], sweetness: ["まろやか"], acidity: ["なめらかな"], bitterness: ["コク(深み)を与える"],
      balance: ["厚みのある", "ねっとりした"], alcohol: ["13%～14%未満"], finish: ["やや長い"],
      evaluation: ["成熟度が高く、豊かな"], temperature: ["11～14度"], glass: ["中庸"],
      vintage: ["2022年"], country: ["フランス"], grape: ["ピノ・グリージョ"],
    },
  },
  {
    id: "cb-fr", color: "white",
    name: "シュナン・ブラン（フランス 2022）",
    note: "ロワール。花梨・蜂蜜と豊かな酸の共存。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["レモンイエロー", "イエロー"], intensity: ["淡い"], viscosity: ["適度な"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["開いている", "フレッシュな"],
      aromaFruit: ["花梨", "柑橘類", "白桃"],
      aromaFlora: ["スイカズラ", "菩提樹"],
      aromaSpice: ["蜂蜜", "花の蜜"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["やや軽い"], sweetness: ["ソフトな"], acidity: ["はつらつとした"], bitterness: ["控えめ"],
      balance: ["ジューシーな", "スリムな"], alcohol: ["12%～13%未満"], finish: ["やや長い"],
      evaluation: ["滑らかで、バランスが良い"], temperature: ["8～10度"], glass: ["小ぶり"],
      vintage: ["2022年"], country: ["フランス"], grape: ["シュナン・ブラン"],
    },
  },
  {
    id: "cb-za", color: "white",
    name: "シュナン・ブラン（南アフリカ 2023）",
    note: "辛口フレッシュ系が主流。トロピカル寄りの果実味。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "レモンイエロー"], intensity: ["淡い"], viscosity: ["適度な"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["開いている", "フレッシュな"],
      aromaFruit: ["パイナップル", "柑橘類", "白桃"],
      aromaFlora: ["ハーブ", "アカシア"],
      aromaSpice: ["花の蜜", "硫黄"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["やや軽い"], sweetness: ["ドライ"], acidity: ["はつらつとした"], bitterness: ["控えめ"],
      balance: ["ジューシーな", "ドライな"], alcohol: ["12%～13%未満"], finish: ["やや短い"],
      evaluation: ["シンプル、フレッシュ感を楽しむ"], temperature: ["8～10度"], glass: ["小ぶり"],
      vintage: ["2023年"], country: ["南アフリカ"], grape: ["シュナン・ブラン"],
    },
  },
  {
    id: "al-es", color: "white",
    name: "アルバリーニョ（スペイン 2023）",
    note: "リアス・バイシャス。潮風・塩味のニュアンスが決め手。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "レモンイエロー"], intensity: ["淡い"], viscosity: ["適度な"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["開いている", "ミネラリー"],
      aromaFruit: ["柑橘類", "白桃", "青リンゴ"],
      aromaFlora: ["ハーブ", "柑橘類の花"],
      aromaSpice: ["海の香り", "貝殻"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["やや軽い"], sweetness: ["ドライ"], acidity: ["爽やかな"], bitterness: ["穏やかな"],
      balance: ["スリムな", "ジューシーな"], alcohol: ["12%～13%未満"], finish: ["やや短い"],
      evaluation: ["エレガントで、ミネラリー"], temperature: ["8～10度"], glass: ["小ぶり"],
      vintage: ["2023年"], country: ["スペイン"], grape: ["アルバリーニョ"],
    },
  },
  {
    id: "pn-us", color: "red",
    name: "ピノ・ノワール（アメリカ 2021）",
    note: "2013・2014年出題。熟した果実味と甘やかな樽。仏よりボリューム感がある。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ルビー", "ガーネット"], intensity: ["やや濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["成熟度が高い", "若々しい"],
      aromaFirst: ["開いている", "濃縮感がある"],
      aromaFruit: ["ブラックチェリー", "ラズベリー", "干しプラム"],
      aromaFlora: ["スミレ", "土"],
      aromaSpice: ["ヴァニラ", "シナモン"],
      aromaImpression: ["若々しい", "木樽からのニュアンス"],
      attack: ["やや強い"], sweetness: ["まろやか"], acidity: ["しなやかな"], tannin: ["ヴィロードのような"],
      balance: ["ふくよかな", "ジューシーな"], alcohol: ["14%以上"], finish: ["やや長い"],
      evaluation: ["成熟度が高く、豊か"], temperature: ["14～16度"], glass: ["バルーン型"],
      vintage: ["2021年"], country: ["アメリカ"], grape: ["ピノ・ノワール"],
    },
  },
  {
    id: "pn-de", color: "red",
    name: "ピノ・ノワール（ドイツ 2021）",
    note: "シュペートブルグンダー。軽やかで酸が伸びる冷涼スタイル。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ルビー", "縁が明るい"], intensity: ["明るい"], viscosity: ["やや軽い"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["控えめ", "華やかな"],
      aromaFruit: ["イチゴ", "ラズベリー", "ブラックチェリー"],
      aromaFlora: ["バラ", "紅茶"],
      aromaSpice: ["シナモン", "丁子"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["やや軽い"], sweetness: ["ドライ"], acidity: ["生き生きとした"], tannin: ["サラサラとした"],
      balance: ["スマートな", "流れるような"], alcohol: ["12%～13%未満"], finish: ["やや短い"],
      evaluation: ["エレガントで、余韻の長い"], temperature: ["14～16度"], glass: ["バルーン型"],
      vintage: ["2021年"], country: ["ドイツ"], grape: ["ピノ・ノワール"],
    },
  },
  {
    id: "cs-fr", color: "red",
    name: "カベルネ・ソーヴィニヨン（フランス 2020）",
    note: "ボルドー。杉・タバコの香りと引き締まったタンニン。米より抑制的。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ダークチェリーレッド", "黒みを帯びた"], intensity: ["濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["若い状態を抜けた", "成熟度が高い"],
      aromaFirst: ["開いている", "深みのある"],
      aromaFruit: ["カシス", "ブラックベリー", "ブラックチェリー"],
      aromaFlora: ["杉", "タバコ"],
      aromaSpice: ["ヴァニラ", "丁子"],
      aromaImpression: ["熟成感が現れている", "木樽からのニュアンス"],
      attack: ["やや強い"], sweetness: ["まろやか"], acidity: ["力強い"], tannin: ["収斂性のある"],
      balance: ["骨格のしっかりした", "堅固な"], alcohol: ["13%～14%未満"], finish: ["やや長い"],
      evaluation: ["複雑性があり、引き締まった"], temperature: ["17～20度"], glass: ["大ぶり"],
      vintage: ["2020年"], country: ["フランス"], grape: ["カベルネ・ソーヴィニヨン"],
    },
  },
  {
    id: "cs-au", color: "red",
    name: "カベルネ・ソーヴィニヨン（オーストラリア 2021）",
    note: "2019年出題。ユーカリ・ミント香が特徴的。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["黒みを帯びた", "ダークチェリーレッド"], intensity: ["濃い"], viscosity: ["強い"],
      appearanceImpression: ["成熟度が高い", "濃縮感が強い"],
      aromaFirst: ["強い", "濃縮感がある"],
      aromaFruit: ["カシス", "ブラックベリー", "ブラックチェリー"],
      aromaFlora: ["ユーカリ", "メントール"],
      aromaSpice: ["ヴァニラ", "ロースト"],
      aromaImpression: ["若々しい", "木樽からのニュアンス"],
      attack: ["強い"], sweetness: ["豊かな"], acidity: ["しなやかな"], tannin: ["力強い"],
      balance: ["豊満な", "力強い"], alcohol: ["14%以上"], finish: ["長い"],
      evaluation: ["濃縮し、力強い"], temperature: ["17～20度"], glass: ["大ぶり"],
      vintage: ["2021年"], country: ["オーストラリア"], grape: ["カベルネ・ソーヴィニヨン"],
    },
  },
  {
    id: "ml-fr", color: "red",
    name: "メルロ（フランス 2020）",
    note: "ボルドー右岸。ふくよかで丸いタンニン、土のニュアンス。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ダークチェリーレッド", "ガーネット"], intensity: ["やや濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["若い状態を抜けた", "成熟度が高い"],
      aromaFirst: ["開いている", "深みのある"],
      aromaFruit: ["ブラックチェリー", "干しプラム", "ブラックベリー"],
      aromaFlora: ["土", "キノコ"],
      aromaSpice: ["ヴァニラ", "甘草"],
      aromaImpression: ["熟成感が現れている", "木樽からのニュアンス"],
      attack: ["やや強い"], sweetness: ["まろやか"], acidity: ["なめらかな"], tannin: ["ヴィロードのような"],
      balance: ["ふくよかな", "骨格のしっかりした"], alcohol: ["13%～14%未満"], finish: ["やや長い"],
      evaluation: ["成熟度が高く、豊か"], temperature: ["17～20度"], glass: ["大ぶり"],
      vintage: ["2020年"], country: ["フランス"], grape: ["メルロ"],
    },
  },
  {
    id: "ml-jp", color: "red",
    name: "メルロ（日本 2021）",
    note: "2018年出題（長野）。穏やかで赤果実寄り、タンニン柔らか。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ルビー", "ダークチェリーレッド"], intensity: ["やや明るい"], viscosity: ["やや軽い"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["控えめ", "開いている"],
      aromaFruit: ["ラズベリー", "ブラックチェリー", "ブルーベリー"],
      aromaFlora: ["紅茶", "土"],
      aromaSpice: ["シナモン", "甘草"],
      aromaImpression: ["若々しい", "第2アロマが強い"],
      attack: ["やや軽い"], sweetness: ["ソフトな"], acidity: ["爽やかな"], tannin: ["溶け込んだ"],
      balance: ["スマートな", "流れるような"], alcohol: ["12%～13%未満"], finish: ["やや短い"],
      evaluation: ["エレガントで、余韻の長い"], temperature: ["14～16度"], glass: ["中庸"],
      vintage: ["2021年"], country: ["日本"], grape: ["メルロ"],
    },
  },
  {
    id: "gr-fr", color: "red",
    name: "グルナッシュ（フランス 2021）",
    note: "2018・2023年出題。イチゴジャムと甘いスパイス。色は淡めなのに高アルコール。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ルビー", "縁が明るい"], intensity: ["やや明るい"], viscosity: ["やや強い"],
      appearanceImpression: ["若い状態を抜けた", "成熟度が高い"],
      aromaFirst: ["開いている", "華やかな"],
      aromaFruit: ["イチゴ", "ラズベリー", "干しプラム"],
      aromaFlora: ["ドライハーブ", "ローリエ"],
      aromaSpice: ["甘草", "シナモン"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["やや強い"], sweetness: ["豊かな"], acidity: ["軽やかな"], tannin: ["溶け込んだ"],
      balance: ["ジューシーな", "ふくよかな"], alcohol: ["14%以上"], finish: ["やや長い"],
      evaluation: ["成熟度が高く、豊か"], temperature: ["14～16度"], glass: ["中庸"],
      vintage: ["2021年"], country: ["フランス"], grape: ["グルナッシュ"],
    },
  },
  {
    id: "gr-es", color: "red",
    name: "グルナッシュ（スペイン 2021）",
    note: "ガルナッチャ。仏より濃く力強いスタイル。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ルビー", "ガーネット"], intensity: ["やや濃い"], viscosity: ["強い"],
      appearanceImpression: ["成熟度が高い", "濃縮感が強い"],
      aromaFirst: ["強い", "濃縮感がある"],
      aromaFruit: ["干しプラム", "ブラックベリー", "イチゴ"],
      aromaFlora: ["ドライハーブ", "土"],
      aromaSpice: ["甘草", "チョコレート"],
      aromaImpression: ["若々しい", "木樽からのニュアンス"],
      attack: ["強い"], sweetness: ["豊かな"], acidity: ["軽やかな"], tannin: ["力強い"],
      balance: ["豊満な", "力強い"], alcohol: ["14%以上"], finish: ["やや長い"],
      evaluation: ["濃縮し、力強い"], temperature: ["17～20度"], glass: ["中庸"],
      vintage: ["2021年"], country: ["スペイン"], grape: ["グルナッシュ"],
    },
  },
  {
    id: "gm-fr", color: "red",
    name: "ガメイ（フランス 2022）",
    note: "2012・2017年出題。MC法由来のキャンディ・バナナ香、軽快。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["紫がかった", "ルビー"], intensity: ["明るい"], viscosity: ["さらっとした"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["開いている", "華やかな"],
      aromaFruit: ["イチゴ", "ラズベリー", "ブルーベリー"],
      aromaFlora: ["バラ", "牡丹"],
      aromaSpice: ["シナモン", "甘草"],
      aromaImpression: ["若々しい", "第2アロマが強い"],
      attack: ["軽い"], sweetness: ["ドライ"], acidity: ["爽やかな"], tannin: ["サラサラとした"],
      balance: ["スマートな", "流れるような"], alcohol: ["12%～13%未満"], finish: ["短い"],
      evaluation: ["シンプル、フレッシュ感を楽しむ"], temperature: ["10～13度"], glass: ["中庸"],
      vintage: ["2022年"], country: ["フランス"], grape: ["ガメイ"],
    },
  },
  {
    id: "nb-it", color: "red",
    name: "ネッビオーロ（イタリア 2019）",
    note: "2012年出題。淡い色に強烈なタンニンと高い酸。バラ・タール。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ガーネット", "オレンジがかった"], intensity: ["やや明るい"], viscosity: ["やや強い"],
      appearanceImpression: ["若い状態を抜けた", "やや熟成した"],
      aromaFirst: ["開いている", "複雑な"],
      aromaFruit: ["ラズベリー", "ブラックチェリー", "干しプラム"],
      aromaFlora: ["バラ", "タバコ"],
      aromaSpice: ["なめし皮", "樹脂"],
      aromaImpression: ["熟成感が現れている", "第2アロマが強い"],
      attack: ["やや強い"], sweetness: ["ドライ"], acidity: ["力強い"], tannin: ["収斂性のある"],
      balance: ["骨格のしっかりした", "堅固な"], alcohol: ["14%以上"], finish: ["長い"],
      evaluation: ["複雑性があり、引き締まった"], temperature: ["17～20度"], glass: ["バルーン型"],
      vintage: ["2019年"], country: ["イタリア"], grape: ["ネッビオーロ"],
    },
  },
  {
    id: "cf-fr", color: "red",
    name: "カベルネ・フラン（フランス 2021）",
    note: "2013・2020年出題。赤果実＋ピーマンの青さ。ロワールは軽やか。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ルビー", "紫がかった"], intensity: ["やや明るい"], viscosity: ["やや軽い"],
      appearanceImpression: ["若々しい", "軽快な"],
      aromaFirst: ["開いている", "華やかな"],
      aromaFruit: ["ラズベリー", "イチゴ", "ブラックチェリー"],
      aromaFlora: ["ピーマン", "スミレ"],
      aromaSpice: ["黒胡椒", "甘草"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["やや軽い"], sweetness: ["ドライ"], acidity: ["生き生きとした"], tannin: ["サラサラとした"],
      balance: ["スマートな", "流れるような"], alcohol: ["12%～13%未満"], finish: ["やや短い"],
      evaluation: ["シンプル、フレッシュ感を楽しむ"], temperature: ["14～16度"], glass: ["中庸"],
      vintage: ["2021年"], country: ["フランス"], grape: ["カベルネ・フラン"],
    },
  },
  {
    id: "mb-ar", color: "red",
    name: "マルベック（アルゼンチン 2021）",
    note: "2017年出題。黒みを帯びた濃い紫、スミレとモカ、豊満。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["黒みを帯びた", "紫がかった"], intensity: ["濃い"], viscosity: ["強い"],
      appearanceImpression: ["成熟度が高い", "濃縮感が強い"],
      aromaFirst: ["強い", "濃縮感がある"],
      aromaFruit: ["ブラックベリー", "干しプラム", "ブルーベリー"],
      aromaFlora: ["スミレ", "ドライハーブ"],
      aromaSpice: ["コーヒー", "ヴァニラ"],
      aromaImpression: ["若々しい", "木樽からのニュアンス"],
      attack: ["強い"], sweetness: ["豊かな"], acidity: ["しなやかな"], tannin: ["緻密"],
      balance: ["豊満な", "力強い"], alcohol: ["14%以上"], finish: ["やや長い"],
      evaluation: ["濃縮し、力強い"], temperature: ["17～20度"], glass: ["大ぶり"],
      vintage: ["2021年"], country: ["アルゼンチン"], grape: ["マルベック"],
    },
  },
  {
    id: "cm-cl", color: "red",
    name: "カルメネール（チリ 2021）",
    note: "2025年出題。濃い外観＋青野菜香＋柔らかいタンニン。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["黒みを帯びた", "ダークチェリーレッド"], intensity: ["濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["成熟度が高い", "濃縮感が強い"],
      aromaFirst: ["開いている", "濃縮感がある"],
      aromaFruit: ["ブラックベリー", "ブラックチェリー", "干しプラム"],
      aromaFlora: ["ピーマン", "黒オリーブ"],
      aromaSpice: ["チョコレート", "ロースト"],
      aromaImpression: ["若々しい", "木樽からのニュアンス"],
      attack: ["やや強い"], sweetness: ["豊かな"], acidity: ["軽やかな"], tannin: ["ヴィロードのような"],
      balance: ["ふくよかな", "ジューシーな"], alcohol: ["14%以上"], finish: ["やや長い"],
      evaluation: ["成熟度が高く、豊か"], temperature: ["17～20度"], glass: ["大ぶり"],
      vintage: ["2021年"], country: ["チリ"], grape: ["カルメネール"],
    },
  },
  {
    id: "zf-us", color: "red",
    name: "ジンファンデル（アメリカ 2021）",
    note: "ジャムのような甘い果実味と高アルコール。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["ルビー", "ダークチェリーレッド"], intensity: ["やや濃い"], viscosity: ["強い"],
      appearanceImpression: ["成熟度が高い", "濃縮感が強い"],
      aromaFirst: ["開いている", "濃縮感がある"],
      aromaFruit: ["ブラックベリー", "干しプラム", "ラズベリー"],
      aromaFlora: ["ドライハーブ", "スミレ"],
      aromaSpice: ["黒胡椒", "チョコレート"],
      aromaImpression: ["若々しい", "第1アロマが強い"],
      attack: ["強い"], sweetness: ["豊かな"], acidity: ["軽やかな"], tannin: ["溶け込んだ"],
      balance: ["豊満な", "ジューシーな"], alcohol: ["14%以上"], finish: ["やや長い"],
      evaluation: ["成熟度が高く、豊か"], temperature: ["14～16度"], glass: ["中庸"],
      vintage: ["2021年"], country: ["アメリカ"], grape: ["ジンファンデル"],
    },
  },

  // ============================================================
  // 実物の模範解答から作った練習ワイン（origin: "past"）
  // ------------------------------------------------------------
  // answers は PAST_ANSWERS と同じ内容で、用語シートに載っている用語だけを残したもの。
  // 各項目の選択数は VOCAB の pick ではなく、その年の正解の語数に合わせる（app.js の pickFor）。
  // 生産地が既存ワインと重複するため、模範解答 比較閲覧の対象からは除外している。
  // ⚠ 元データは会員限定公開の正解を個人ブログが転記したもので、原本と未照合。
  // ============================================================
  {
    id: "px-2025s1-ch-fr", color: "white", origin: "past",
    name: "シャルドネ（フランス 2022）｜2025年ソムリエ①",
    note: "「やや濃い」と分類されながら中身は淡い〜やや濃いの境界。シャブリ型で樽が弱く、味わいはエレガント側に振れている。",
    caveat: "アルコールは原本の「12.0〜12.9%」を用語シートの表記へ読み替えている。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["グリーンがかった", "イエロー"], intensity: ["やや濃い"], viscosity: ["適度な"],
      appearanceImpression: ["若々しい", "成熟度が高い"],
      aromaFirst: ["控えめ", "フレッシュな", "ミネラリー"],
      aromaFruit: ["柑橘類", "青リンゴ", "リンゴ", "洋梨"],
      aromaFlora: ["フレッシュ・アーモンド"],
      aromaSpice: ["石灰", "貝殻", "海の香り", "パン・ドゥ・ミ", "トースト", "乳製品"],
      aromaImpression: ["若々しい", "第1アロマが強い", "ニュートラル"],
      attack: ["やや軽い"], sweetness: ["ドライ"], acidity: ["爽やかな", "軽やかな"],
      bitterness: ["控えめ", "穏やかな"],
      balance: ["スリムな", "ドライな"], alcohol: ["12%～13%未満"], finish: ["やや短い", "やや長い"],
      evaluation: ["シンプル、フレッシュ感を楽しむ", "エレガントで、ミネラリー"],
      temperature: ["8度未満", "8～10度"], glass: ["小ぶり", "バルーン型"],
      vintage: ["2022年"], country: ["フランス"], grape: ["シャルドネ"],
    },
  },
  {
    id: "px-2025s3-zf-us", color: "red", origin: "past",
    name: "ジンファンデル（アメリカ 2023）｜2025年ソムリエ③",
    note: "濃淡は「やや濃い」で濃い赤と淡い赤の中間。タンニンは溶け込んでおり、バランスは豊満・ジューシー。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["紫がかった", "ルビー", "ラズベリーレッド"], intensity: ["やや濃い"], viscosity: ["やや強い", "強い"],
      appearanceImpression: ["若々しい", "成熟度が高い"],
      aromaFirst: ["開いている", "強い", "濃縮感がある"],
      aromaFruit: ["イチゴ", "カシス", "干しプラム", "乾燥イチジク"],
      aromaFlora: ["牡丹", "ローリエ", "ドライハーブ"],
      aromaSpice: ["シナモン", "ナツメグ", "甘草", "乾いた肉", "なめし皮", "チョコレート"],
      aromaImpression: ["第1アロマが強い", "木樽からのニュアンス"],
      attack: ["強い"], sweetness: ["まろやか", "豊かな"], acidity: ["なめらかな", "しなやかな"],
      tannin: ["溶け込んだ"],
      balance: ["豊満な", "ジューシーな"], alcohol: ["14%以上"], finish: ["やや長い"],
      evaluation: ["成熟度が高く、豊か", "濃縮し、力強い"],
      temperature: ["17～20度"], glass: ["中庸", "大ぶり", "チューリップ型"],
      vintage: ["2023年"], country: ["アメリカ"], grape: ["ジンファンデル"],
    },
  },
  {
    id: "px-2024we4-sg-it", color: "red", origin: "past",
    name: "サンジョヴェーゼ（イタリア 2020）｜2024年WE④",
    note: "淡い赤の骨格型。色は「やや明るい」なのにタンニンは力強い・緻密で、バランスは骨格のしっかりした側。",
    caveat: "アルコールは原本が「やや強め・熱さを感じる」という当時の様式の表記だったため、用語シートの度数レンジへ読み替えている。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある", "艶のある"],
      color: ["オレンジがかった", "縁が明るい", "ルビー", "ラズベリーレッド"],
      intensity: ["やや明るい"], viscosity: ["やや強い", "強い"],
      appearanceImpression: ["若い状態を抜けた", "成熟度が高い"],
      aromaFirst: ["開いている", "複雑な"],
      aromaFruit: ["ラズベリー", "ブルーベリー", "カシス", "干しプラム"],
      aromaFlora: ["バラ", "スミレ", "ゼラニウム", "ドライハーブ", "タバコ", "キノコ", "トマト", "黒オリーブ"],
      aromaSpice: ["丁子", "シナモン", "ナツメグ", "甘草", "ヴァニラ", "乾いた肉", "なめし皮", "動物的なニュアンス", "鉄分"],
      aromaImpression: ["熟成感が現れている", "第1アロマが強い", "木樽からのニュアンス"],
      attack: ["強い"], sweetness: ["ドライ"], acidity: ["なめらかな", "しなやかな"],
      tannin: ["力強い", "緻密"],
      balance: ["骨格のしっかりした", "堅固な", "力強い"], alcohol: ["13%～14%未満"], finish: ["やや長い", "長い"],
      evaluation: ["成熟度が高く、豊か", "エレガントで、余韻の長い", "複雑性があり、引き締まった"],
      temperature: ["14～16度", "17～20度"], glass: ["中庸", "大ぶり"],
      vintage: ["2020年"], country: ["イタリア"], grape: ["サンジョヴェーゼ"],
    },
  },
  {
    id: "px-2023s3-me-jp", color: "red", origin: "past",
    name: "メルロ（日本 2018）｜2023年ソムリエ③",
    note: "本来は濃い赤の品種なのに、正解は完全に淡い赤のコメント。品種ではなく目の前の状態でタイプを決める例。",
    caveat: "第一印象の原本には「チャーミングな」が含まれるが、2025年度の用語シートから削除された表現のため除いている。アルコールは原本の「やや軽め・中程度」を度数レンジへ読み替えた。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある", "艶のある"],
      color: ["縁が明るい", "ルビー", "ラズベリーレッド"],
      intensity: ["やや明るい", "やや濃い"], viscosity: ["やや強い"],
      appearanceImpression: ["若い状態を抜けた", "成熟度が高い"],
      aromaFirst: ["控えめ", "深みのある"],
      aromaFruit: ["ラズベリー", "ブルーベリー", "干しプラム"],
      aromaFlora: ["メントール", "シダ", "ドライハーブ", "タバコ", "キノコ", "土"],
      aromaSpice: ["ナツメグ", "ヴァニラ", "ロースト", "乾いた肉", "なめし皮"],
      aromaImpression: ["熟成感が現れている", "第1アロマが強い", "木樽からのニュアンス"],
      attack: ["やや強い"], sweetness: ["ソフトな", "まろやか"], acidity: ["なめらかな", "しなやかな"],
      tannin: ["サラサラとした", "溶け込んだ"],
      balance: ["スマートな", "流れるような"], alcohol: ["12%～13%未満"], finish: ["やや長い", "長い"],
      evaluation: ["エレガントで、余韻の長い"],
      temperature: ["14～16度", "17～20度"], glass: ["中庸"],
      vintage: ["2018年"], country: ["日本"], grape: ["メルロ"],
    },
  },
  {
    id: "px-2023we3-gr-fr", color: "red", origin: "past",
    name: "グルナッシュ（フランス 2021）｜2023年WE③",
    note: "淡い赤の骨格型のなかでも濃い側。濃淡は「やや濃い・濃い」で、アタックは強い・インパクトのある。",
    caveat: "アルコールは原本が「やや強め・熱さを感じる」という当時の様式の表記だったため、用語シートの度数レンジへ読み替えている。",
    answers: {
      clarity: ["澄んだ"], brightness: ["輝きのある"],
      color: ["紫がかった", "ルビー", "ラズベリーレッド"],
      intensity: ["やや濃い", "濃い"], viscosity: ["やや強い", "強い"],
      appearanceImpression: ["若々しい", "成熟度が高い", "濃縮感が強い"],
      aromaFirst: ["開いている", "強い", "濃縮感がある"],
      aromaFruit: ["ブルーベリー", "カシス", "ブラックチェリー", "干しプラム"],
      aromaFlora: ["ローリエ", "ドライハーブ", "紅茶", "トマト", "黒オリーブ"],
      aromaSpice: ["丁子", "シナモン", "ナツメグ", "甘草", "ヴァニラ", "乾いた肉", "鉄分", "グリエ", "煙・燻製", "チョコレート"],
      aromaImpression: ["第1アロマが強い", "木樽からのニュアンス"],
      attack: ["強い", "インパクトのある"], sweetness: ["ドライ"], acidity: ["なめらかな", "しなやかな"],
      tannin: ["力強い"],
      balance: ["骨格のしっかりした", "力強い"], alcohol: ["13%～14%未満"], finish: ["やや長い", "長い"],
      evaluation: ["成熟度が高く、豊か", "濃縮し、力強い"],
      temperature: ["17～20度"], glass: ["中庸", "大ぶり"],
      vintage: ["2021年"], country: ["フランス"], grape: ["グルナッシュ"],
    },
  },
];

// ------------------------------------------------------------
// 主要品種フラッシュカード データ
// front: 品種名 / back: 特徴（外観・香り・味わい・決め手・主産地）
// countries: 生産地フィルタ用（試験で問われる主要生産国）
// ------------------------------------------------------------
const GRAPES = [
  // ---- 白 ----
  { name: "シャルドネ", color: "white", countries: ["フランス", "アメリカ", "オーストラリア", "日本"],
    appearance: "産地・樽の有無で幅広い。樽熟成は黄金色がかったイエロー、粘性やや強い",
    aroma: "リンゴ、洋梨、白桃。樽由来のヴァニラ・トースト・バター",
    taste: "まろやかな酸、厚みのあるボディ",
    key: "品種特有の香りが少なく「樽・乳製品」のニュアンスで判断。冷涼産地（シャブリ等）はミネラルと高い酸",
    byCountry: {
      "フランス": "シャブリ等の冷涼系は火打石・ミネラルと鋭い酸。ブルゴーニュの樽熟成はナッツ・トーストと厚み",
      "アメリカ": "熟した白桃・パイナップル。バター・ヴァニラの樽香が強く豊満、酸はなめらか",
      "オーストラリア": "明確な果実味とトースト香。近年は酸を残した引き締まったスタイルも増加",
      "日本": "穏やかな果実味と控えめな樽使い。全体にすっきりと上品",
    },
    region: "フランス（ブルゴーニュ）、アメリカ、オーストラリア" },
  { name: "ソーヴィニヨン・ブラン", color: "white", countries: ["フランス", "ニュージーランド", "チリ"],
    appearance: "グリーンがかった淡いレモンイエロー",
    aroma: "柑橘類、ハーブ、切りたての芝生。NZはパッションフルーツが顕著",
    taste: "はつらつとした酸、フレッシュでドライ",
    key: "ハーブ・草の香り＋高い酸。NZ産はトロピカル寄り",
    byCountry: {
      "フランス": "ロワールは柑橘＋火打石のミネラル。ハーブ香は控えめで引き締まった辛口",
      "ニュージーランド": "パッションフルーツ＋ハーブが全開。香りが最も派手で酸もはっきり",
      "チリ": "柑橘＋ややトロピカル。NZほど香りが強くない中間的スタイル",
    },
    region: "フランス（ロワール）、ニュージーランド、チリ" },
  { name: "リースリング", color: "white", countries: ["ドイツ", "フランス", "オーストラリア"],
    appearance: "グリーンがかった淡いレモンイエロー",
    aroma: "白い花、柑橘、青リンゴ。熟成でペトロール（灯油）香",
    taste: "鋭い酸と残糖のバランス。アルコール低め（独）",
    key: "残糖＋高い酸＋ペトロール香の三点セット",
    byCountry: {
      "ドイツ": "残糖と鋭い酸の甘辛バランス。アルコール低め（11%未満が目安）",
      "フランス": "アルザスは辛口で骨格しっかり。アルコールは中程度",
      "オーストラリア": "辛口でライムとペトロール香が明確。酸は直線的",
    },
    region: "ドイツ、フランス（アルザス）、オーストラリア" },
  { name: "甲州", color: "white", countries: ["日本"],
    appearance: "無色に近いほど淡い",
    aroma: "控えめな柑橘・白い花。ニュートラル",
    taste: "穏やかで軽く、後味に柑橘の内皮のような苦味",
    key: "香りの弱さ・外観の淡さ・低めのアルコール",
    region: "日本（山梨）" },
  { name: "ゲヴュルツトラミネール", color: "white", countries: ["フランス", "ドイツ"],
    appearance: "やや濃いイエロー",
    aroma: "ライチ、バラ、白い花、スパイス",
    taste: "酸は穏やか、アルコールのボリューム感",
    key: "ライチの華やかなアロマ＋低い酸＋高アルコール",
    byCountry: {
      "フランス": "アルザスは豊満で高アルコール。ライチ・バラが濃厚",
      "ドイツ": "やや軽やかで繊細。酸も比較的残る",
    },
    region: "フランス（アルザス）、ドイツ" },
  { name: "ミュスカデ", color: "white", countries: ["フランス"],
    appearance: "グリーンがかった淡い色調",
    aroma: "控えめな柑橘・青リンゴ。シュール・リー由来の酵母香",
    taste: "軽快でドライ、フレッシュな酸",
    key: "全体の軽さとニュートラルさ。甲州との識別は酵母ニュアンス",
    region: "フランス（ロワール）" },
  { name: "シュナン・ブラン", color: "white", countries: ["フランス", "南アフリカ"],
    appearance: "中程度のイエロー",
    aroma: "花梨、蜂蜜、白い花",
    taste: "豊かな酸。辛口〜甘口までタイプが幅広い",
    key: "蜂蜜・花梨香と高い酸の共存",
    byCountry: {
      "フランス": "ロワールは辛口〜甘口まで幅広く、蜂蜜・花梨の熟した香り",
      "南アフリカ": "辛口でフレッシュな柑橘系が主流。価格帯も幅広い",
    },
    region: "フランス（ロワール）、南アフリカ" },
  { name: "ヴィオニエ", color: "white", countries: ["フランス"],
    appearance: "やや濃いイエロー",
    aroma: "アプリコット、白桃、白い花",
    taste: "酸は穏やか、豊潤で高アルコール",
    key: "アプリコット香＋低酸のボリューム感（ゲヴュルツと迷ったらライチの有無）",
    region: "フランス（ローヌ北部）" },
  { name: "アルバリーニョ", color: "white", countries: ["スペイン"],
    appearance: "淡いレモンイエロー",
    aroma: "柑橘、白桃、潮風・ミネラル",
    taste: "爽やかな酸、ほのかな塩味と苦味",
    key: "海を思わせる塩気のニュアンス",
    region: "スペイン（リアス・バイシャス）" },
  { name: "トロンテス", color: "white", countries: ["アルゼンチン"],
    appearance: "淡い〜中程度のイエロー",
    aroma: "マスカット、白い花、ライチ系の華やかさ",
    taste: "辛口で酸は中程度",
    key: "華やかなアロマなのに辛口。ゲヴュルツより酸が高い",
    region: "アルゼンチン" },
  { name: "ピノ・グリージョ（ピノ・グリ）", color: "white", countries: ["イタリア", "フランス"],
    appearance: "やや濃いイエロー。銅色（グリ）を帯びることも",
    aroma: "洋梨、白桃、アーモンド。イタリア産はニュートラル寄り",
    taste: "イタリアは軽快でドライ、フレッシュな酸",
    key: "産地でスタイルが二分：イタリア＝軽快辛口、アルザス＝豊満でコクあり",
    byCountry: {
      "イタリア": "北東部産は軽快・ドライ・ニュートラル。酸はフレッシュで飲み口すっきり",
      "フランス": "アルザスのピノ・グリは豊満で蜂蜜・スモークの香り。残糖のあるタイプも",
    },
    region: "イタリア（北東部）、フランス（アルザス）" },
  // ---- 赤 ----
  { name: "ピノ・ノワール", color: "red", countries: ["フランス", "ニュージーランド", "アメリカ", "ドイツ"],
    appearance: "明るいルビー、縁は明るい",
    aroma: "イチゴ、ラズベリー、バラ、土・紅茶",
    taste: "生き生きとした酸、サラサラとしたタンニン",
    key: "淡い色調＋赤系果実＋シルキーな口当たり",
    byCountry: {
      "フランス": "赤果実＋土・キノコの複雑さ。酸としなやかさのバランス重視",
      "ニュージーランド": "チェリー系の明るく濃いめの果実味。色調もやや濃い",
      "アメリカ": "熟した果実味と甘やかな樽。ボリューム感がある",
      "ドイツ": "シュペートブルグンダーと呼ばれる。軽やかで酸が伸びる冷涼スタイル",
    },
    region: "フランス（ブルゴーニュ）、ニュージーランド、アメリカ" },
  { name: "カベルネ・ソーヴィニヨン", color: "red", countries: ["フランス", "アメリカ", "チリ", "オーストラリア"],
    appearance: "黒みを帯びた濃いダークチェリーレッド",
    aroma: "カシス、杉、冷涼産地はピーマン。樽のヴァニラ・ロースト",
    taste: "力強いタンニン、しっかりした骨格",
    key: "濃い色＋カシス＋強いタンニン",
    byCountry: {
      "フランス": "ボルドーは杉・タバコの香りと引き締まったタンニン。メルロとのブレンドが基本",
      "アメリカ": "完熟カシスで濃厚。樽香豊かでタンニンも甘く熟す",
      "チリ": "ピーマン・ハーブのニュアンスが出やすい。果実味は充実",
      "オーストラリア": "ユーカリ・ミント香が特徴的",
    },
    region: "フランス（ボルドー）、アメリカ、チリ、オーストラリア" },
  { name: "メルロ", color: "red", countries: ["フランス", "日本"],
    appearance: "濃いめのダークチェリーレッド",
    aroma: "ブラックチェリー、干しプラム、土",
    taste: "タンニンは緻密でまろやか、ふくよかな果実味",
    key: "カベルネより柔らかく丸い印象",
    byCountry: {
      "フランス": "ボルドー右岸はふくよかで土のニュアンス。熟したプラム",
      "日本": "長野産は穏やかで赤果実寄り。タンニン柔らかくチャーミング",
    },
    region: "フランス（ボルドー右岸）、日本（長野）" },
  { name: "シラー（シラーズ）", color: "red", countries: ["フランス", "オーストラリア"],
    appearance: "紫がかった濃い色調",
    aroma: "黒胡椒、ブラックベリー、スミレ。豪はチョコレート",
    taste: "豊満で力強い、豊かなタンニン",
    key: "黒胡椒のスパイス香",
    byCountry: {
      "フランス": "ローヌ北部は黒胡椒・スミレが際立つ引き締まったスタイル",
      "オーストラリア": "シラーズはジャム・チョコレートの甘やかで豊満なスタイル",
    },
    region: "フランス（ローヌ北部）、オーストラリア" },
  { name: "サンジョヴェーゼ", color: "red", countries: ["イタリア"],
    appearance: "ルビー〜ガーネット",
    aroma: "赤系果実、ドライハーブ、紅茶",
    taste: "力強い酸＋収斂性のあるタンニン",
    key: "酸とタンニンの両方が強い",
    region: "イタリア（トスカーナ）" },
  { name: "テンプラニーリョ", color: "red", countries: ["スペイン"],
    appearance: "中〜濃いルビー",
    aroma: "干しプラム、イチゴジャム、ヴァニラ・ココナッツ（米国樽）",
    taste: "酸はなめらか、熟した果実味",
    key: "アメリカンオーク由来のヴァニラ・ココナッツ香",
    region: "スペイン（リオハ）" },
  { name: "ガメイ", color: "red", countries: ["フランス"],
    appearance: "紫がかった明るいルビー",
    aroma: "イチゴ、ラズベリー、バナナ・キャンディ（MC法）",
    taste: "軽快でフレッシュな酸、タンニン軽め",
    key: "キャンディ・バナナ香＋軽さ。MBAと迷ったら綿あめ香の強さ",
    region: "フランス（ボージョレ）" },
  { name: "グルナッシュ", color: "red", countries: ["フランス", "スペイン"],
    appearance: "やや明るいルビー、早くオレンジがかる",
    aroma: "イチゴジャム、干しプラム、甘いスパイス",
    taste: "酸は低め、高アルコール、甘やかな果実味",
    key: "色は淡めなのにアルコールが高い",
    byCountry: {
      "フランス": "南ローヌはイチゴジャム＋ハーブ（ガリーグ）。高アルコール",
      "スペイン": "ガルナッチャ。より濃く力強いスタイルもある",
    },
    region: "フランス（ローヌ南部）、スペイン（ガルナッチャ）" },
  { name: "ネッビオーロ", color: "red", countries: ["イタリア"],
    appearance: "明るめのガーネット、縁はオレンジがかる",
    aroma: "バラ、タール、チェリー、なめし皮",
    taste: "強烈なタンニンと力強い酸",
    key: "淡い色と裏腹の強いタンニン・高い酸",
    region: "イタリア（ピエモンテ）" },
  { name: "ジンファンデル", color: "red", countries: ["アメリカ"],
    appearance: "中〜濃いルビー",
    aroma: "ブラックベリージャム、甘いスパイス",
    taste: "甘やかな果実味、高アルコール、タンニン中程度",
    key: "ジャムのような甘い果実味と高アルコール",
    region: "アメリカ（カリフォルニア）" },
  { name: "マスカット・ベーリーA", color: "red", countries: ["日本"],
    appearance: "明るいルビー",
    aroma: "イチゴキャンディ、綿あめ",
    taste: "軽快、サラサラとしたタンニン",
    key: "綿あめ・キャンディ香（フラネオール）",
    region: "日本" },
  { name: "カベルネ・フラン", color: "red", countries: ["フランス"],
    appearance: "やや明るいルビー",
    aroma: "ラズベリー、ピーマンの青さ、スミレ、鉛筆の芯",
    taste: "カベルネ・ソーヴィニヨンより軽やか。フレッシュな酸、タンニン中程度",
    key: "赤系果実＋ピーマン香の組み合わせ。過去出題あり（2013・2020 いずれも仏）",
    region: "フランス（ロワール、ボルドー右岸）" },
  { name: "マルベック", color: "red", countries: ["アルゼンチン", "フランス"],
    appearance: "黒みを帯びた濃い紫",
    aroma: "ブラックベリー、干しプラム、スミレ、モカ",
    taste: "豊満でタンニンは緻密、酸は穏やか",
    key: "濃い色＋スミレ＋甘やかな果実。シラーズと迷ったら黒胡椒の有無。過去出題あり（2017 アルゼンチン）",
    byCountry: {
      "アルゼンチン": "メンドーサ産は完熟果実で豊満。樽由来のモカ・ヴァニラ",
      "フランス": "カオールは「黒ワイン」と呼ばれる堅牢でタンニックなスタイル",
    },
    region: "アルゼンチン（メンドーサ）、フランス（カオール）" },
  { name: "カルメネール", color: "red", countries: ["チリ"],
    appearance: "黒みを帯びた濃いルビー",
    aroma: "ブラックベリー、ピーマン・青唐辛子、チョコレート",
    taste: "タンニンはまろやか、酸穏やかで豊か",
    key: "濃い外観＋青野菜香＋柔らかいタンニン。カベルネより酸・タンニンが穏やか。過去出題あり（2025 チリ）",
    region: "チリ" },
  { name: "ピノタージュ", color: "red", countries: ["南アフリカ"],
    appearance: "濃いルビー",
    aroma: "ブラックベリー、干しプラム、燻製・タール、甘いバナナ的ニュアンス",
    taste: "豊かな果実味と力強いタンニン",
    key: "スモーキーさと甘い果実の同居",
    region: "南アフリカ" },
];


// ------------------------------------------------------------
// 過去の出題品種データ
// items    : ワインエキスパート二次試験の出題（品種別ランキングの集計対象）
// sommelier: 同じ年のソムリエ二次試験の出題（参考表示のみ・ランキングには含めない）
//
// 出典1（品種・生産国）: ワイン受験.com「過去の出題ワインの品種と生産国」(2026-08取得)
//   https://www.wine-jyuken.com/second_exam/kakonosyutudai
// 出典2（ヴィンテージ・出題番号・ソムリエ試験分）: 個人ブログ「ニライカナイCH」
//   2026年版 二次試験対策シリーズ (2026-09取得) https://niraikanao-ch1.com/tastingmatome-2026/
//   ⚠ 出典2は個人ブログの転記であり未検証。品種・生産国は出典1と突き合わせて一致を確認済み。
//   ヴィンテージと出題番号は出典2のみが根拠なので、公式資料で見かけたら上書きすること。
//
// type: "white" | "red" | "other"（その他の酒類）
// no  : 本試験での出題番号（不明な場合は省略）
// ------------------------------------------------------------
const PAST_EXAMS = [
  { year: 2025, items: [
    { no: 1, type: "white", name: "リースリング", country: "オーストラリア", vintage: 2023 },
    { no: 2, type: "white", name: "ソーヴィニヨン・ブラン", country: "フランス", vintage: 2024 },
    { no: 3, type: "red", name: "テンプラニーリョ", country: "スペイン" },
    { no: 4, type: "red", name: "カルメネール", country: "チリ", vintage: 2021 },
    { type: "other", name: "スコッチ・ウイスキー" },
  ], sommelier: [
    { no: 1, type: "white", name: "シャルドネ", country: "フランス", vintage: 2022 },
    { no: 2, type: "white", name: "甲州", country: "日本", vintage: 2024 },
    { no: 3, type: "red", name: "ジンファンデル", country: "アメリカ", vintage: 2023 },
  ]},
  { year: 2024, items: [
    { no: 1, type: "white", name: "ミュスカデ", country: "フランス", vintage: 2021 },
    { no: 2, type: "white", name: "シャルドネ", country: "日本", vintage: 2023 },
    { no: 3, type: "red", name: "カベルネ・ソーヴィニヨン", country: "アメリカ", vintage: 2021 },
    { no: 4, type: "red", name: "サンジョヴェーゼ", country: "イタリア", vintage: 2020 },
    { type: "other", name: "バーボン・ウイスキー" },
  ], sommelier: [
    { no: 1, type: "white", name: "リースリング", country: "ドイツ", vintage: 2021 },
    { no: 2, type: "white", name: "ソーヴィニヨン・ブラン", country: "フランス", vintage: 2022 },
    { no: 3, type: "red", name: "シラー", country: "オーストラリア", vintage: 2021 },
  ]},
  { year: 2023, items: [
    { no: 1, type: "white", name: "ソーヴィニヨン・ブラン", country: "チリ", vintage: 2021 },
    { no: 2, type: "white", name: "リースリング", country: "オーストラリア", vintage: 2021 },
    { no: 3, type: "red", name: "グルナッシュ", country: "フランス", vintage: 2021 },
    { no: 4, type: "red", name: "テンプラニーリョ", country: "スペイン", vintage: 2017 },
    { type: "other", name: "ジン" },
  ], sommelier: [
    { no: 1, type: "white", name: "ソーヴィニヨン・ブラン", country: "フランス", vintage: 2021 },
    { no: 2, type: "red", name: "マルベック", country: "アルゼンチン", vintage: 2020 },
    { no: 3, type: "red", name: "メルロー", country: "日本", vintage: 2018 },
  ]},
  { year: 2022, items: [
    { no: 1, type: "white", name: "ソーヴィニヨン・ブラン", country: "ニュージーランド", vintage: 2019 },
    { no: 2, type: "white", name: "甲州", country: "日本", vintage: 2021 },
    { no: 3, type: "red", name: "カベルネ・ソーヴィニヨン", country: "アメリカ", vintage: 2019 },
    { no: 4, type: "red", name: "シラー", country: "フランス", vintage: 2018 },
    { type: "other", name: "オー・ド・ヴィー・ド・キルシュ" },
  ]},
  { year: 2021, items: [
    { no: 1, type: "white", name: "リースリング", country: "フランス", vintage: 2019 },
    { no: 2, type: "white", name: "ヴィオニエ", country: "フランス", vintage: 2019 },
    { no: 3, type: "red", name: "テンプラニーリョ", country: "スペイン", vintage: 2017 },
    { no: 4, type: "red", name: "カベルネ・ソーヴィニヨン", country: "チリ", vintage: 2018 },
    { type: "other", name: "テキーラ" },
  ], sommelier: [
    { no: 1, type: "white", name: "シャルドネ", country: "フランス", vintage: 2019 },
    { no: 2, type: "red", name: "サンジョヴェーゼ", country: "イタリア", vintage: 2018 },
    { no: 3, type: "red", name: "メルロー", country: "アメリカ", vintage: 2017 },
  ]},
  { year: 2020, items: [
    { type: "white", name: "トロンテス", country: "アルゼンチン" },
    { type: "white", name: "シャルドネ", country: "フランス" },
    { type: "red", name: "カベルネ・フラン", country: "フランス" },
    { type: "red", name: "ピノ・ノワール", country: "ニュージーランド" },
    { type: "other", name: "ラム" },
  ]},
  { year: 2019, items: [
    { type: "white", name: "ソーヴィニヨン・ブラン", country: "ニュージーランド" },
    { type: "white", name: "甲州", country: "日本" },
    { type: "red", name: "サンジョヴェーゼ", country: "イタリア" },
    { type: "red", name: "カベルネ・ソーヴィニヨン", country: "オーストラリア" },
    { type: "other", name: "紹興酒" },
  ]},
  { year: 2018, items: [
    { type: "white", name: "リースリング", country: "ドイツ" },
    { type: "white", name: "シャルドネ", country: "オーストラリア" },
    { type: "red", name: "メルロ", country: "日本" },
    { type: "red", name: "グルナッシュ", country: "フランス" },
    { type: "other", name: "ベネディクティン" },
  ]},
  { year: 2017, items: [
    { type: "white", name: "ソーヴィニヨン・ブラン", country: "チリ" },
    { type: "white", name: "ミュスカデ", country: "フランス" },
    { type: "red", name: "ガメイ", country: "フランス" },
    { type: "red", name: "マルベック", country: "アルゼンチン" },
    { type: "other", name: "サンブーカ" },
  ]},
  { year: 2016, items: [
    { type: "white", name: "リースリング", country: "フランス" },
    { type: "white", name: "シャルドネ", country: "アメリカ" },
    { type: "red", name: "シラー", country: "オーストラリア" },
    { type: "red", name: "テンプラニーリョ", country: "スペイン" },
    { type: "other", name: "泡盛" },
  ]},
  { year: 2015, items: [
    { type: "white", name: "リースリング", country: "オーストラリア" },
    { type: "white", name: "シャルドネ", country: "フランス" },
    { type: "red", name: "シラー", country: "フランス" },
    { type: "red", name: "カベルネ・ソーヴィニヨン", country: "アメリカ" },
    { type: "other", name: "コニャック" },
    { type: "other", name: "アマレット" },
  ]},
  { year: 2014, items: [
    { type: "white", name: "リースリング", country: "ドイツ" },
    { type: "white", name: "ソーヴィニヨン・ブラン", country: "ニュージーランド" },
    { type: "red", name: "ピノ・ノワール", country: "アメリカ" },
    { type: "red", name: "シラー", country: "フランス" },
    { type: "other", name: "シングルモルト・ウイスキー" },
    { type: "other", name: "ガリアーノ" },
  ]},
  { year: 2013, items: [
    { type: "white", name: "甲州", country: "日本" },
    { type: "white", name: "ソーヴィニヨン・ブラン", country: "フランス" },
    { type: "red", name: "カベルネ・フラン", country: "フランス" },
    { type: "red", name: "ピノ・ノワール", country: "アメリカ" },
    { type: "other", name: "カルヴァドス" },
    { type: "other", name: "トウニー・ポート" },
  ]},
  { year: 2012, items: [
    { type: "white", name: "リースリング", country: "オーストラリア" },
    { type: "white", name: "シャルドネ", country: "フランス" },
    { type: "red", name: "ガメイ", country: "フランス" },
    { type: "red", name: "ネッビオーロ", country: "イタリア" },
    { type: "other", name: "ホワイト・キュラソー（コアントロー）" },
    { type: "other", name: "カルヴァドス" },
  ]},
  { year: 2011, items: [
    { type: "white", name: "シャルドネ", country: "アメリカ" },
    { type: "white", name: "リースリング", country: "フランス" },
    { type: "red", name: "シラー", country: "オーストラリア" },
    { type: "red", name: "テンプラニーリョ", country: "スペイン" },
    { type: "other", name: "ドライ・ヴェルモット" },
    { type: "other", name: "ウォッカ" },
  ]},
];
